Fix setting displayMode value in case of AUTO mode
smartdevicelink/sdl_hmi pull request #322
Opened 2020-04-14 12:43 UTC by YarikMamykin

Implements/Fixes [#310](https://github.com/smartdevicelink/sdl_hmi/issues/310)

This PR is **not ready** for review.

### Testing Plan
Manual testing

### Summary
In case of hmi settings update there was no condition for `displayMode=AUTO` coming.
Added next condition - if `displayMode=AUTO` comes from SDL then response message should contain `displayMode=DAY`, otherwise return as is. 

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-04-17 13:54 UTC, AKalinich-Luxoft commented on app/model/HmiSettingsModel.js
> +  defineAutoTimeValue: function() {
@YarikMamykin please provide a description here

2020-04-22 08:44 UTC, YarikMamykin commented on app/model/HmiSettingsModel.js
> +  defineAutoTimeValue: function() {
@AKalinich-Luxoft done in https://github.com/smartdevicelink/sdl_hmi/pull/322/commits/dd02926f0092e6131eb1692410cc98ee425fd543

2020-04-24 08:44 UTC, YarikMamykin commented
@theresalech this PR is ready for Livio team review. Please notice that https://github.com/smartdevicelink/sdl_hmi/issues/310 is **not** a regression issue.

2020-10-14 17:58 UTC, iCollin requested changes

2020-10-14 17:58 UTC, iCollin commented on app/model/HmiSettingsModel.js
> +    time = parseInt(time.substring(0, time.indexOf(':')));
```suggestion
    var time = new Date().getHours();
```

2020-10-14 17:58 UTC, iCollin commented on app/model/HmiSettingsModel.js
> +        result.displayMode = (data.displayMode == 'AUTO' ? this.defineAutoTimeValue() : data.displayMode);
```suggestion
        result.displayMode = (data.displayMode === 'AUTO' ? this.defineAutoTimeValue() : data.displayMode);
```

2020-10-14 19:33 UTC, AKalinich-Luxoft commented on app/model/HmiSettingsModel.js
> +    time = parseInt(time.substring(0, time.indexOf(':')));
@iCollin fixed in https://github.com/smartdevicelink/sdl_hmi/pull/322/commits/eac8199a67cb7b453d4791209e4a86e61638e6ec

2020-10-14 19:33 UTC, AKalinich-Luxoft commented on app/model/HmiSettingsModel.js
> +        result.displayMode = (data.displayMode == 'AUTO' ? this.defineAutoTimeValue() : data.displayMode);
@iCollin fixed in https://github.com/smartdevicelink/sdl_hmi/pull/322/commits/eac8199a67cb7b453d4791209e4a86e61638e6ec

2020-10-15 03:15 UTC, merged