Fix/fix type error on file remove
smartdevicelink/sdl_hmi pull request #332
Opened 2020-04-14 19:43 UTC by AKalinich-Luxoft

Fixes #300 

This PR is **not ready** for review.

### Testing Plan
Covered with manual testing

### Summary
Changelog:
- Replaced multiple getters with a single variable referring to the same object.
- Added one more check to verify if `vrHelp` item contains `image` object or not as it might be not mandatory according to HMI_API

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-04-15 11:36 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
>        params.fileType === 'GRAPHIC_PNG' || params.fileType === 'GRAPHIC_BMP' ||
@AKalinich-Luxoft , I would advise to place condition `(params.fileType === 'GRAPHIC_PNG' || params.fileType === 'GRAPHIC_BMP' || params.fileType === 'GRAPHIC_JPEG')` into a single variable...

Or even make some lambda for that purpose, e.g:
```suggestion
      var file_is_pic = function (fileType) {
        var check_list = [ 'GRAPHIC_PNG', 'GRAPHIC_BMP', 'GRAPHIC_JPEG' ]
        for (var item in check_list) {
          if (fileType === item) {
            return true;
          }
        }
        return false;
      }
```

2020-04-15 14:20 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
>        params.fileType === 'GRAPHIC_PNG' || params.fileType === 'GRAPHIC_BMP' ||
@YarikMamykin good idea. However lambda is overhead here.
See https://github.com/smartdevicelink/sdl_hmi/pull/332/commits/ea6d7cf4860d59ef8e18d78749a13ae26bdaa0f3

2020-10-21 15:09 UTC, ShobhitAd requested changes

2020-10-21 15:09 UTC, ShobhitAd commented on app/model/sdl/Abstract/Model.js
> +          params.fileName.length == app_model.constantTBTParams.turnIcon.value.length) {
Wouldn't you get the same result if you replaced these conditions with 
```suggestion
            app_model.constantTBTParams.turnIcon.value === params.fileName) {
```

2020-10-22 19:24 UTC, theresalech commented
Hi @AKalinich-Luxoft, we are nearing the end of our development timeline and will need to merge this PR by EOD Monday (10/26) in order to guarantee its inclusion in the SDL HMI 5.4 Release. Can you please let us know if you have any concerns with addressing our review on this PR by that time? Thank you!

2020-10-23 00:07 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +      if (app_model.appIcon.indexOf(params.fileName) != -1 &&
@ShobhitAd fixed in https://github.com/smartdevicelink/sdl_hmi/pull/332/commits/122e39649b6c14a42f13bac8cd4a6412d75fb591

2020-10-23 00:08 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          params.fileName.length == app_model.constantTBTParams.turnIcon.value.length) {
@ShobhitAd agree, you suggestion is much obvious. Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/332/commits/122e39649b6c14a42f13bac8cd4a6412d75fb591

2020-10-23 00:09 UTC, AKalinich-Luxoft commented
> Hi @AKalinich-Luxoft, we are nearing the end of our development timeline and will need to merge this PR by EOD Monday (10/26) in order to guarantee its inclusion in the SDL HMI 5.4 Release. Can you please let us know if you have any concerns with addressing our review on this PR by that time? Thank you!

@theresalech thank you for letting me know! I addressed all Livio comments and hopefully you will be able to review and approve this PR soon.

2020-10-23 18:03 UTC, ShobhitAd approved these changes

2020-10-23 18:03 UTC, merged