Hotfix/314 No warnings code in response in case of invalid image paths provided
smartdevicelink/sdl_hmi pull request #344
Opened 2020-04-21 23:17 UTC by YarikMamykin

Implements/Fixes [#314] 

This PR is **not ready]** for review.

### Testing Plan
Manual testing

### Summary
When invalid system path to icon was provided through request params there was no validation of latter one. Because of that there was no WARNINGS code in response from HMI.

Changes provided:
1. Added validation mechanism for icons system paths.
2. Updated result response message structure (added section with "response info" if one provided by HMI).
3. Updated all affected rpcs with icons paths check.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-04-22 00:08 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +  imageCheckList: [],
@YarikMamykin I think this should be a map where key is a request id and value is an array of paths to check. This is because you may have two consequent requests from SDL with images to validate. And images from first of them might not be validated before the second one calls `validateImages`

2020-04-22 00:09 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +  validateImages: function(callback, imageList) {
@YarikMamykin please add `request_id` as the first parameter according to comment above

2020-04-22 00:15 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          var fullpath = 'file://' + SDL.SDLModel.imageCheckList[i].path;
@YarikMamykin don't hardcode the protocol, as its possible that somebody is using web server and paths are accessible via http. Its better to compare paths after `://`.

2020-04-22 00:15 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +            SDL.SDLModel.imageCheckList[i].checkResult = true;
@YarikMamykin you can add break here

2020-04-22 00:15 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          var fullpath = 'file://' + SDL.SDLModel.imageCheckList[i].path;
@YarikMamykin same as above

2020-04-22 00:17 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +    callback(failed);
@YarikMamykin as I can see you actually don't need to know amount of fails in your callbacks. I propose to pass just true/false to callback function - that would be much simpler

2020-04-22 00:20 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          if(failed > 0) {
Assuming `failed` is bool
```suggestion
          FFW.UI.sendUIResult(
              failed ? SDL.SDLModel.data.resultCode.WARNINGS : SDL.SDLModel.data.resultCode.SUCCESS,
              request.id, 
              request.method, 
              failed ? "Requested image(s) not found" : null
              );
```

2020-04-22 00:21 UTC, AKalinich-Luxoft commented on app/view/sdl/AlertManeuverPopUp.js
> +    iconsValid: false,
@YarikMamykin `iconsAreValid` ?
Also, please add description why do you need that flag

2020-04-22 00:24 UTC, AKalinich-Luxoft commented on ffw/NavigationRPC.js
> +          delete JSONMessage.result.info;
@YarikMamykin why so tricky? Its better to remove this at line 509 and check instead if (info) then JSONMessage.result.info = info

2020-04-22 00:25 UTC, AKalinich-Luxoft commented on app/controller/NavigationController.js
> +    isPng: function(imagePath) {
@YarikMamykin please add the description for these 2 functions

2020-04-22 00:30 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +    callback(failed);
@YarikMamykin also, don't forget to delete key from `imageCheckList` map once all images in array checked. its a potential memory leak

2020-04-22 00:37 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +      this.imageCheckList.push({
@YarikMamykin I believe this should be a set, not a vector. I mean this is a common situation when request elements are using the same icon from several places, so `imageList` parameter may contain duplicated values. You should remove duplicates just to avoid spending of extra time on verification of the same image. I am also not sure how JS works when two images are trying to access the same source at the same moment.

2020-04-23 17:07 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +  imageCheckList: [],
@AKalinich-Luxoft done in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/0e61c5bdb52e408ef86ab077930e76b8e0799756

2020-04-23 17:07 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +  validateImages: function(callback, imageList) {
@AKalinich-Luxoft done in 0e61c5b

2020-04-23 17:07 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +          var fullpath = 'file://' + SDL.SDLModel.imageCheckList[i].path;
@AKalinich-Luxoft done in 0e61c5b

2020-04-23 17:07 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +            SDL.SDLModel.imageCheckList[i].checkResult = true;
@AKalinich-Luxoft done in 0e61c5b

2020-04-23 17:08 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +          var fullpath = 'file://' + SDL.SDLModel.imageCheckList[i].path;
@AKalinich-Luxoft done in 0e61c5b

2020-04-23 17:08 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +    callback(failed);
@AKalinich-Luxoft done in 0e61c5b

2020-04-23 17:08 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +          if(failed > 0) {
@AKalinich-Luxoft done in 0e61c5b

2020-04-23 17:09 UTC, YarikMamykin commented on app/view/sdl/AlertManeuverPopUp.js
> +    iconsValid: false,
@AKalinich-Luxoft done in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/c6053e6dd05d0df2e6bf00dfc083b0797ea6cf92

2020-04-23 17:10 UTC, YarikMamykin commented on ffw/NavigationRPC.js
> +          delete JSONMessage.result.info;
@AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/291c1bc25b0712044800adb06ec185d5625a5563

2020-04-23 17:10 UTC, YarikMamykin commented on app/controller/NavigationController.js
> +    isPng: function(imagePath) {
@AKalinich-Luxoft done in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/291c1bc25b0712044800adb06ec185d5625a5563

2020-04-23 17:10 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +    callback(failed);
@AKalinich-Luxoft done in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/0e61c5bdb52e408ef86ab077930e76b8e0799756

2020-04-23 17:11 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +      this.imageCheckList.push({
@AKalinich-Luxoft done in 
https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/0e61c5bdb52e408ef86ab077930e76b8e0799756

2020-05-06 14:04 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +    for(var i = 0; i < imageList.length; i++) {
@YarikMamykin turn to dark side of magic and use its power:
```
const filteredImageList = imageList.filter(function(item, pos) {
    return imageList.indexOf(item) == pos;
});

filteredImageList.forEach(image => {
  this.imageCheckList[requestID].push({
          'path': image,
          'checkResult': null
        });
});
```

2020-05-06 14:07 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +    for(var i = 0; i < SDL.SDLModel.imageCheckList[requestID].length; i++) {
@YarikMamykin consider using of `forEach` + arrow functions to make this much shorter and easier to read

2020-05-06 14:10 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +      callback(0);
@YarikMamykin 
```suggestion
      callback(false);
```

2020-05-06 14:11 UTC, AKalinich-Luxoft commented on ffw/NavigationRPC.js
> +            'method': method,
@YarikMamykin 
```suggestion
            'method': method
```

2020-05-06 14:12 UTC, AKalinich-Luxoft commented on ffw/UIRPC.js
> +            // Get images paths
@YarikMamykin redundant comment

2020-05-06 14:12 UTC, AKalinich-Luxoft commented on app/controller/NavigationController.js
> +      img_extension = '.png';
@YarikMamykin 
```suggestion
      const img_extension = '.png';

```

2020-05-06 16:20 UTC, YarikMamykin commented on app/model/sdl/Abstract/AppModel.js
> +          if(!SDL.NavigationController.isPng(image)) {
@AKalinich-Luxoft I'm not sure about this, because as I see not all RPC require check for PNG format of image.

2020-05-06 17:21 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +    for(var i = 0; i < imageList.length; i++) {
@AKalinich-Luxoft reworked in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/635901b631a35a19062f2c627b68c6c629a09ca0

2020-05-06 17:21 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +    for(var i = 0; i < SDL.SDLModel.imageCheckList[requestID].length; i++) {
@AKalinich-Luxoft reworked in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/635901b631a35a19062f2c627b68c6c629a09ca0

2020-05-06 17:22 UTC, YarikMamykin commented on app/model/sdl/Abstract/Model.js
> +      callback(0);
@AKalinich-Luxoft reworked in 635901b

2020-05-06 17:22 UTC, YarikMamykin commented on ffw/UIRPC.js
> +            // Get images paths
@AKalinich-Luxoft 
 removed in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/a41e76b05e96c49600fa554dd14800f8bc1c3174

2020-05-06 17:23 UTC, YarikMamykin commented on app/controller/NavigationController.js
> +      img_extension = '.png';
@AKalinich-Luxoft `const` added in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/d7f74e6b3fc3c68776f9f16d2f19a2042af6334f

2020-05-06 17:23 UTC, YarikMamykin commented on ffw/NavigationRPC.js
> +            'method': method,
@AKalinich-Luxoft removed in d7f74e6

2020-05-15 10:56 UTC, YarikMamykin commented
@theresalech please notice, that this pull request is ready for Livio Code Review.

2020-05-19 15:06 UTC, theresalech commented
@YarikMamykin we will work to include this fix in the next release of the SDL HMI (5.4).

2020-10-01 10:54 UTC, YarikMamykin commented
@theresalech please notice, that this pull request is ready for Livio Code Review.

2020-10-09 14:15 UTC, ShobhitAd requested changes

2020-10-13 21:12 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +   * @param requestID - request id, to which icons belong
@ShobhitAd fixed in https://github.com/smartdevicelink/sdl_hmi/pull/344/commits/245a6a17f7b4839a6aab3ec0b70d0ecbbcf56be7

2020-10-13 21:14 UTC, AKalinich-Luxoft commented on app/controller/NavigationController.js
> +              delete params.turnList[i].turnIcon;
@ShobhitAd I believe this is somehow related to template images proposal. PNG files are the only files which support alpha-transparency and looks like in some places HMI design requires exactly such type of images to make a proper template images overlay. Here might be another reasons though.

2020-10-13 21:35 UTC, AKalinich-Luxoft commented
Conflicts have been resolved

2020-10-19 19:05 UTC, ShobhitAd approved these changes

2020-10-19 19:06 UTC, merged