Fix/326 no display mode change in nav view
smartdevicelink/sdl_hmi pull request #369
Opened 2020-06-02 12:02 UTC by YarikMamykin

Implements/Fixes [#326](https://github.com/smartdevicelink/sdl_hmi/issues/326)

This PR is **ready** for review.

### Testing Plan
Manual testing

### Summary
In case of display mode value change there was no logic for changing display mode in navigation view. Besides that mechanics of DisplayMode selection view was changed: since now this control element just changes value of `SDL.SDLModel.data.imageMode` property and all interested observers are notified each time it changes to process such behavior with appropriate callback.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-06-02 12:02 UTC, YarikMamykin commented
@theresalech please notice that this PR is ready for Livio Team Code Review.

2020-10-14 20:21 UTC, jacobkeeler requested changes

2020-10-14 20:21 UTC, jacobkeeler commented
@YarikMamykin also fix merge conflicts

2020-10-15 04:23 UTC, AKalinich-Luxoft commented on app/controller/sdl/Abstract/Controller.js
> +        }
@jacobkeeler redundant code removed in https://github.com/smartdevicelink/sdl_hmi/pull/369/commits/abe9cc55b9b3e890a48ce49e75f88bed695b553c

2020-10-15 04:24 UTC, AKalinich-Luxoft commented
> @YarikMamykin also fix merge conflicts

@jacobkeeler conflicts have been resolved in https://github.com/smartdevicelink/sdl_hmi/pull/369/commits/8e27920fb936f41b885d8eb4598d8e04929609c3

2020-10-15 14:56 UTC, jacobkeeler approved these changes

2020-10-15 14:56 UTC, merged