Fix success response code on jpeg images
smartdevicelink/sdl_hmi pull request #372
Opened 2020-06-04 20:12 UTC by YarikMamykin

Implements/Fixes 
[#319](https://github.com/smartdevicelink/sdl_hmi/issues/319)
[#321](https://github.com/smartdevicelink/sdl_hmi/issues/321)
[#329](https://github.com/smartdevicelink/sdl_hmi/issues/329)

This PR is **ready** for review.

**WARNING! This PR should be merged only after https://github.com/smartdevicelink/sdl_hmi/pull/344**

### Testing Plan
Manual testing

### Summary
Enhanced image validation function and added check for template non-png images.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-06-05 07:38 UTC, YarikMamykin commented
@theresalech please notice that this PR is ready for Livio Team Code Review.

2020-11-05 21:39 UTC, jacobkeeler requested changes

2020-11-05 21:39 UTC, jacobkeeler commented on app/view/sdl/AlertPopUp.js
> +        self.reason = 'WARNINGS';
```suggestion
        self.reason = failed ? 'WARNINGS' : 'SUCCESS';
```

2020-11-05 21:39 UTC, jacobkeeler commented on ffw/UIRPC.js
> +                  imageList.push(request.params.vrHelp[i].image.value);
Should there be an `isPng` check for the images in this function?

2020-11-05 21:40 UTC, jacobkeeler commented
@YarikMamykin also fix merge conflicts

2020-11-06 01:22 UTC, iCollin reviewed
should this be case - insensitive?

edit: i’m not reviewing this PR just had this comment saved from taking a look previously

2020-11-09 22:27 UTC, AKalinich-Luxoft commented
@iCollin @jacobkeeler because of a lot of conflicts and some architectural changes introduced in release 7.0 it makes sense to completely change this fix.
Closed in favor of #462

2020-11-09 22:27 UTC, closed without merging