Fix/exit close cloud connection
smartdevicelink/sdl_hmi pull request #410
Opened 2020-10-05 12:13 UTC by LitvinenkoIra

Implements/Fixes [#316](https://github.com/smartdevicelink/sdl_hmi/issues/316)

This PR is **ready** for review.

### Summary
Current PR adds the ability to send BC.OnExitApplication with **CLOSE_ClOUD_CONNECTION** reason

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-10-05 12:13 UTC, LitvinenkoIra commented
@theresalech this PR is ready for Livio review

2020-10-08 16:28 UTC, iCollin requested changes

2020-10-08 16:28 UTC, iCollin commented on app/controller/sdl/Abstract/Controller.js
> +      });
```suggestion
      let model = SDL.SDLController.getApplicationModel(params.appID);
      exitCommands.forEach(command => {
        model.addCommand(command)
      });
```

2020-10-13 17:37 UTC, AKalinich-Luxoft commented on app/controller/sdl/Abstract/Controller.js
> +      });
@iCollin fixed in https://github.com/smartdevicelink/sdl_hmi/pull/410/commits/ff8177e6b1cec5f0ea2b6be74f8a68662e2028ad

2020-10-13 18:21 UTC, iCollin approved these changes

2020-10-13 18:21 UTC, merged