Fix/app permissions list
smartdevicelink/sdl_hmi pull request #411
Opened 2020-10-06 13:08 UTC by LitvinenkoIra

Fixes [#148](https://github.com/SmartDeviceLink/sdl_hmi/issues/148)

This PR is **ready** for review.

### Summary
Current PR contains an additional check for displaying propper application permissions.
Note: goToStates is removed from permissionsFriendlyMessageUpdate to prevent switching to app permissions after an application is activated.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-10-06 13:08 UTC, LitvinenkoIra commented
@theresalech This PR is ready for Livio review

2020-10-14 21:13 UTC, jacobkeeler approved these changes

2020-10-15 13:48 UTC, jacobkeeler requested changes

2020-10-15 13:48 UTC, jacobkeeler commented on app/controller/SettingsController.js
> -      SDL.States.goToStates('settings.policies.appPermissions');
This change seems irrelevant, it probably shouldn't be in this PR.

2020-10-19 18:42 UTC, jacobkeeler commented
Closing in favor of #424

2020-10-19 18:42 UTC, closed without merging