Fix UNSUPPORTED_RESOURCE result code for images
smartdevicelink/sdl_hmi pull request #450
Opened 2020-11-02 21:54 UTC by AKalinich-Luxoft

Fixes #443 and #442 

This PR is **not ready** for review.

### Testing Plan
Covered by manual tests

### Summary
Make HMI to respond with the proper result code in case when STATIC image is received. Also removed redundant and commented code to make things cleaner.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-03 12:59 UTC, Ypostolov approved these changes

2020-11-04 15:49 UTC, theresalech commented
@AKalinich-Luxoft, given the size of these changes and time constraints (Steering Committee is currently reviewing Core 7.0 Release Candidate for approval, and release of both Core 7.0 and SDL HMI 5.4 are planned for tomorrow, 11/5), we will plan to review this PR for the following SDL HMI release.

2020-11-09 15:08 UTC, jacobkeeler requested changes

2020-11-10 01:35 UTC, AKalinich-Luxoft commented on ffw/TTSRPC.js
> -          }
@jacobkeeler nice catch. Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/450/commits/3fef8dc711af9ecbe8c9f0c1f4cedae8b5158d99

2020-11-10 01:36 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          if (formattedImgPath.endsWith(path)) {
@jacobkeeler I remember there was an issue when `this.src` returns me just `icon.png` without an absolute path so validation was never finished, however I am not able to reproduce this now. I reverted that change in https://github.com/smartdevicelink/sdl_hmi/pull/450/commits/3fef8dc711af9ecbe8c9f0c1f4cedae8b5158d99

2020-11-10 19:26 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          if (formattedImgPath.endsWith(path)) {
@jacobkeeler seems like I found what was the issue. It is happening when some RPC passes image with relative path to validation. For example, `Alert` uses image `images/sdl/Warning.png` however this is a relative path so in case if this will be validated, `formattedImgPath` will never be equal to `path` here and element with required index will never be found and set. As a result, image validation result will never be received back by RPC regardless of another images types and extensions.
I simplified that function and just set index as a property of `this` and use it to set the element by that index in the array so this `for` loop is not required anymore. I pushed that commit into #462  - https://github.com/smartdevicelink/sdl_hmi/pull/462/commits/62be9bc1f3ccad2b5a6e1911fca1fae47df71a87 because it can't be verified without these changes.
Actually, these two pull requests have a lot of intersections and I can propose to merge one PR into another and review them together. Otherwise, we can review and merged them separately, but some conflicts should be resolved then.
Please let me know what do you think about that?

2020-11-16 15:24 UTC, jacobkeeler commented on app/model/sdl/Abstract/Model.js
> +          if (formattedImgPath.endsWith(path)) {
Eh, considering that my review of this PR is almost done as-is, and we would need to fix merge conflicts in any case, I say that we can just go forward with reviewing them separately

2020-11-16 20:11 UTC, jacobkeeler commented on ffw/UIRPC.js
> +          params
As a note, if a PerformInteraction request is sent with MANUAL_ONLY, Core will mark the response as `success: false` if an UNSUPPORTED_RESOURCE code is sent.

2020-11-16 20:55 UTC, jacobkeeler commented on ffw/UIRPC.js
> +          params
Seems this is the case with `Alert` as well.

2020-11-16 21:25 UTC, jacobkeeler commented on ffw/UIRPC.js
> +          params
@AKalinich-Luxoft Perhaps we should keep it so these cases return `WARNINGS` for now? That or we could submit a fix for this issue alongside this PR. Let me know your thoughts on the matter

2020-11-16 21:58 UTC, AKalinich-Luxoft commented on ffw/UIRPC.js
> +          params
@jacobkeeler so the fix was to return UNSUPPORTED_RESOURCE instead of WARNINGS in these cases.
Regarding `success:false` - do you mean wrong SDL behavior in that case? If so, I agree that new SDL issue should be created and we can work on fix for that further

2020-11-16 22:02 UTC, AKalinich-Luxoft commented on ffw/UIRPC.js
> +          params
@jacobkeeler I also see the issues like https://github.com/smartdevicelink/sdl_core/issues/1596 which looks like describe the same case

2020-11-17 15:09 UTC, jacobkeeler commented on ffw/UIRPC.js
> +          params
hmm, don't know exactly what happened with that issue, the one difference in the description is that it specifies is that `UNSUPPORTED_RESOURCE` is sent for `VR.PerformInteraction` instead of `UI.PerformInteraction`. At the moment, it looks like the SDL HMI will send `WARNINGS` for `VR.PerformInteraction` if unsupported phonemes are used, so it's possible that I attempted that and misinterpreted the results. Seems that the issue is still present though, so I will reopen the issue.

2020-11-17 15:52 UTC, jacobkeeler commented on ffw/UIRPC.js
> +          params
Alright, I think I can approve this PR for now and I'll submit a fix for https://github.com/smartdevicelink/sdl_core/issues/1596 to go along with this

2020-11-17 15:52 UTC, jacobkeeler approved these changes

2020-11-17 15:53 UTC, merged