Fix sending of redundant notifications on app activation
smartdevicelink/sdl_hmi pull request #460
Opened 2020-11-03 22:55 UTC by AKalinich-Luxoft

Fixes #455 

This PR is **not ready** for review.

### Testing Plan
Covered by manual checklist

### Summary
Looks like HMI sends redundant `OnUpdateFile` and `onUpdateSubMenu` notifications when application was deactivated and activated again. After clarifications, looks like it makes more sense to send such notifications just once for each submenu and for each image which was not loaded properly. Also, updated logic of sending `OnUpdateSubMenu` items to make a partial update only for visible part of menu.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-04 13:06 UTC, Ypostolov approved these changes

2021-02-15 17:16 UTC, ShobhitAd commented
@AKalinich-Luxoft please resolve merge conflicts on PR

2021-02-16 02:04 UTC, AKalinich-Luxoft commented
> @AKalinich-Luxoft please resolve merge conflicts on PR

@ShobhitAd conflicts have been resolved in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/d5a51121b7d696a31cb9d93af99310b383af132d

2021-03-08 13:59 UTC, ShobhitAd requested changes
Similar to how a `menuId` is removed from the `cachedSubMenuIdsList` when a `DeleteSubMenu` is received, shouldn't filenames be removed from `cachedIconFileNamesList` when an `onFileRemoved` is received?

2021-03-08 13:59 UTC, ShobhitAd commented on app/controller/sdl/Abstract/Controller.js
> +        if (model.cachedIconFileNamesList.indexOf(fileName) < 0) {
```suggestion
        if (!model.cachedIconFileNamesList.includes(fileName)) {
```
might be clearer since we only want to check if that fileName exists in the list

2021-03-08 13:59 UTC, ShobhitAd commented on app/controller/sdl/Abstract/Controller.js
> +        if (model.cachedSubmenuIdsList.indexOf(menuID) < 0) {
```suggestion
        if (!model.cachedSubmenuIdsList.includes(menuID)) {
```

2021-03-08 19:56 UTC, AKalinich-Luxoft commented
> Similar to how a `menuId` is removed from the `cachedSubMenuIdsList` when a `DeleteSubMenu` is received, shouldn't filenames be removed from `cachedIconFileNamesList` when an `onFileRemoved` is received?

@ShobhitAd agree, makes sense. Added in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/fc0ec0196e42cd5a8b20429f28b7b030fdb7c894

2021-03-08 19:57 UTC, AKalinich-Luxoft commented on app/controller/sdl/Abstract/Controller.js
> +        if (model.cachedIconFileNamesList.indexOf(fileName) < 0) {
@ShobhitAd fixed in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/fc0ec0196e42cd5a8b20429f28b7b030fdb7c894

2021-03-08 19:57 UTC, AKalinich-Luxoft commented on app/controller/sdl/Abstract/Controller.js
> +        if (model.cachedSubmenuIdsList.indexOf(menuID) < 0) {
@ShobhitAd fixed in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/fc0ec0196e42cd5a8b20429f28b7b030fdb7c894

2021-03-08 21:59 UTC, ShobhitAd approved these changes

2021-03-08 21:59 UTC, merged