Fix success response code on jpeg images
smartdevicelink/sdl_hmi pull request #462
Opened 2020-11-09 22:26 UTC by AKalinich-Luxoft

Fixes 
[#319](https://github.com/smartdevicelink/sdl_hmi/issues/319)
[#321](https://github.com/smartdevicelink/sdl_hmi/issues/321)
[#329](https://github.com/smartdevicelink/sdl_hmi/issues/329)

This PR is **ready** for review.

### Testing Plan
Manual testing

### Summary
Enhanced image validation function and added check for template non-png images.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-17 16:55 UTC, jacobkeeler requested changes
Also fix merge conflicts

2020-11-17 17:44 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          info : "Template image extension is not valid"
@jacobkeeler fixed in https://github.com/smartdevicelink/sdl_hmi/pull/462/commits/fd93ebfeab939e56fec00794e5e44fef39b8a920

2020-11-17 17:44 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          info : null
@jacobkeeler fixed in https://github.com/smartdevicelink/sdl_hmi/pull/462/commits/fd93ebfeab939e56fec00794e5e44fef39b8a920

2020-11-17 17:44 UTC, AKalinich-Luxoft commented on app/model/sdl/Abstract/Model.js
> +          info : "Requested image(s) not found"
@jacobkeeler fixed in https://github.com/smartdevicelink/sdl_hmi/pull/462/commits/fd93ebfeab939e56fec00794e5e44fef39b8a920

2020-11-17 17:44 UTC, AKalinich-Luxoft commented
> Also fix merge conflicts

@jacobkeeler conflicts have been resolved in https://github.com/smartdevicelink/sdl_hmi/pull/462/commits/8eabfcc4de5786be1cdc0460e9b764c855f5e4f7

2020-11-18 22:19 UTC, jacobkeeler approved these changes

2020-11-18 22:19 UTC, merged