Feature/custom playback rate
smartdevicelink/sdl_hmi pull request #469
Opened 2020-12-09 15:59 UTC by jacobkeeler

Implements #221  

This PR is **ready** for review.

### Testing Plan
Manually test with various startTimes, endTimes, and countRates

### Summary
Adds support for countRate parameter in SetMediaClockTimer

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-06 15:13 UTC, ShobhitAd requested changes

2021-01-06 15:13 UTC, ShobhitAd commented on app/model/sdl/MediaModel.js
>      var number, str = '', hrs = 0, min = 0, sec = 0;
Since this PR is making changes to the existing time calculations it might be a good idea to rename the `number` variable to something to something more descriptive (Maybe `timestamp` or something similar)

2021-01-11 17:10 UTC, jacobkeeler commented on app/model/sdl/MediaModel.js
>      var number, str = '', hrs = 0, min = 0, sec = 0;
Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/469/commits/3ed2cdf4a709f502c63728e380fb461730663d6d

2021-01-11 17:11 UTC, jacobkeeler commented
Addressed comment in https://github.com/smartdevicelink/sdl_hmi/pull/469/commits/3ed2cdf4a709f502c63728e380fb461730663d6d. Also fixed an issue I found where UI.Show would cause the timer to stop

2021-01-12 17:02 UTC, ShobhitAd approved these changes

2021-01-14 14:13 UTC, merged