[SDL 0305] Homogenize TextFieldName
smartdevicelink/sdl_hmi pull request #473
Opened 2020-12-16 18:53 UTC by iCollin

Implements/Fixes https://github.com/smartdevicelink/sdl_hmi/issues/371

This PR is **ready** for review.

### Summary
add timeToDestination to capabilities
remove navigationText references
fix navigation template mainField assignment

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-02-02 19:43 UTC, jacobkeeler requested changes

2021-02-02 19:43 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +                },
Should add turnText as well

2021-02-03 15:54 UTC, iCollin commented on capabilities/display_capabilities.js
> +                },
added in https://github.com/smartdevicelink/sdl_hmi/pull/473/commits/d77ce1f760582accfb3e4f82942218ec4a704f2e

2021-02-03 20:38 UTC, jacobkeeler requested changes
Hmmm, it looks like there are several other places where `timeToDestination` and `turnText` will need to be added (twice in `UIRPC.js` and once in `data.js`).

That said, it's probably worth changing this so that they all get the capabilities from the same place

2021-02-04 16:33 UTC, iCollin commented
> That said, it's probably worth changing this so that they all get the capabilities from the same place

While I agree, I looked into this and doing it properly would take a bit.
Unfortunately I feel like there is some pressure to get this feature in a good state quickly, so I have just made the necessary changes for now.

2021-02-04 17:05 UTC, jacobkeeler approved these changes

2021-02-09 18:15 UTC, merged