Feature/sdl 0238 keyboard enhancements
smartdevicelink/sdl_hmi pull request #474
Opened 2020-12-18 14:30 UTC by AKalinich-Luxoft

Implements/Fixes [#nnnn](github.com/smartdevicelink/sdl_core/issues/nnnn)

This PR is **[ready / not ready]** for review.

### Testing Plan
[Describe how your changes will be tested]

### Summary
[Summary of PR changes]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-07 03:36 UTC, AKalinich-Luxoft commented
@ashwink11, this PR is ready for review

2021-01-07 12:55 UTC, ashwink11 commented
@AKalinich-Luxoft changes approved from the Ford side.

2021-01-08 14:36 UTC, KhrystynaDubovyk commented
@JackLivio This PR is ready for Livio ready. Thank you!

2021-01-08 16:03 UTC, ashwink11 commented
@jordynmackool  this PR is ready for review. Thanks!

2021-01-22 19:46 UTC, jacobkeeler requested changes
Note that this is a partial review due to the fact that there are some pending revisions which might affect the implementation of this slightly (see https://github.com/smartdevicelink/sdl_evolution/pull/1117)

2021-01-26 16:40 UTC, AKalinich-Luxoft commented on app/controller/sdl/KeyboardController.js
> +    unsupportedKeyboardSymbols: [ '^' ],
@jacobkeeler it's just a random symbol we decided to chose for our testing purposes and to demonstrate that this part of functionality works as expected

2021-01-26 16:44 UTC, AKalinich-Luxoft commented on app/controller/sdl/KeyboardController.js
> +            false;
@AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_hmi/pull/474/commits/02c7de3fc7457bc4abe5732264b05b5b40f33906

2021-01-26 16:44 UTC, AKalinich-Luxoft commented on app/controller/sdl/KeyboardController.js
> +     * @description Disables or enables charaters depeding on global properties
@jacobkeeler fixed in https://github.com/smartdevicelink/sdl_hmi/pull/474/commits/02c7de3fc7457bc4abe5732264b05b5b40f33906

2021-01-26 16:44 UTC, AKalinich-Luxoft commented on app/controller/sdl/KeyboardController.js
> +          SDL.Keyboard.deactivate();
@AKalinich-Luxoft fixed in https://github.com/smartdevicelink/sdl_hmi/pull/474/commits/02c7de3fc7457bc4abe5732264b05b5b40f33906

2021-01-26 16:44 UTC, AKalinich-Luxoft commented on app/controller/sdl/KeyboardController.js
> +            SDL.Keyboard.searchBar.input.type = 'text';
@jacobkeeler fixed in https://github.com/smartdevicelink/sdl_hmi/pull/474/commits/02c7de3fc7457bc4abe5732264b05b5b40f33906

2021-02-03 21:35 UTC, jordynmackool commented
@AKalinich-Luxoft the proposal markdown file has been updated per the revisions included in the accepted with revisions review issue: [Revise SDL-0238 Keyboard Enhancements](https://github.com/smartdevicelink/sdl_evolution/pull/1119).

Please make the needed updates to this PR and then tag @jacobkeeler to review when ready. Thanks!

2021-02-08 14:24 UTC, AKalinich-Luxoft commented
@jacobkeeler this PR has been updated according to revision and ready for Livio review

2021-02-08 16:15 UTC, jacobkeeler commented on app/controller/sdl/KeyboardController.js
> +    unsupportedKeyboardSymbols: [ '^' ],
Alright, but I don't see any reason for this feature to be included in the first place, as it's not mentioned in the proposal at any point

2021-02-08 16:17 UTC, jacobkeeler commented on app/controller/sdl/KeyboardController.js
> +    unsupportedKeyboardSymbols: [ '^' ],
That said, considering it's a fairly small feature, there isn't much point in removing it at this point, so I'll mark this as resolved

2021-02-08 20:46 UTC, jacobkeeler commented on app/controller/sdl/KeyboardController.js
> +    unsupportedKeyboardSymbols: [ '^' ],
Never mind, I didn't notice it initially, but I now see that this functionality is explicitly listed in the proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0238-Keyboard-Enhancements.md#change-in-keyboardproperties-struct

2021-02-09 20:48 UTC, jacobkeeler approved these changes
As a note, I did notice that the documentation for this feature says that the HMI should avoid duplicating custom keys, but this implementation does not do so. That said, I would see this as an optional optimization, so I am approving this PR.

2021-02-12 14:03 UTC, merged