Feature/sdl 0264 separating the change of audible status and the change of hmi status
smartdevicelink/sdl_hmi pull request #499
Opened 2021-03-04 05:18 UTC by Yuki-Kanadome-Nexty

Implements/Fixes [#275 ](github.com/smartdevicelink/sdl_core/issues/275)

This PR is **ready** for review.

### Testing Plan
This change will be tested with sdl_core 7.0 + PR at [smartdevicelink/sdl_core#3634](https://github.com/smartdevicelink/sdl_core/pull/3634).

### Summary
This is a response to changes made by SDL 0264.
When sending OnEventChanged (PHONE_CALL, true / false), OnAppDeactivated / OnAppActivated is sent to the app which HMI Level is FULL.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-06-24 15:04 UTC, jacobkeeler requested changes
While there are a few changes I would suggest, after looking more into this I don't think this PR is needed. The original behavior of the HMI was to stay on the phone screen after the phone call was ended, so I don't see any reason to add this behavior now.

2021-06-28 13:28 UTC, jordynmackool commented
@Yuki-Kanadome-Nexty please see Jacobs's feedback above and let us know your thoughts. If you agree with Jacob, we can then close this PR and the associated issue.

2021-07-06 13:10 UTC, jordynmackool commented
@Yuki-Kanadome-Nexty Following up to ensure you saw Jacobs comment [here](https://github.com/smartdevicelink/sdl_hmi/pull/499#pullrequestreview-691873436). If we don't hear from you this week, we will move forward with closing the Issue/ PR on 2021-07-12.

2021-07-08 07:12 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Sorry for delay our response.
Does your suggestion mean below?
 Ex. Music screen - (phone call) -> Phone call screen - (phone call is ends) -> Stay phone call screen
If our recognition is wrong, could you please explain the details.
Our proposal is to return to the screen before phone call like below.
 Ex. Music screen - (phone call) -> Phone call screen - (phone call is ends) -> Music screen
Therefore, we made a commit the modification.

2021-07-13 15:15 UTC, jacobkeeler commented
Ah, I can see how this case would make sense. It does get a bit more complicated if you leave the phone screen before ending the call though:

Music app screen - (phone call) -> Phone call screen -> App list - (activate nav app) -> Navigation app screen -> Phone call screen - (phone call ends) -> Music app screen?

Perhaps we should clear `redisplayAppID` if the user leaves the phone call screen?

2021-07-13 17:33 UTC, jacobkeeler requested changes

2021-07-13 17:33 UTC, jacobkeeler commented on app/model/sdl/Abstract/data.js
> +    redisplayAppID: null,
Perhaps this should be included in `PhoneModel.js` instead?

2021-07-13 17:42 UTC, jacobkeeler commented
Closing as review has moved to #576

2021-07-13 17:42 UTC, closed without merging