Fix HMI connection to Policy Manager during PTU
smartdevicelink/sdl_hmi pull request #540
Opened 2021-03-24 02:06 UTC by AKalinich-Luxoft

Fixes #527

This PR is **ready** for review.

### Testing Plan
Has been tested manually against the following scenario:

1. Activate app and consent device.
=> SDL starts PTU and sends SDL.OnStatusUpdate(UPDATE_NEEDED, UPDATING)
2. Send Ignition Off
3. Start SDL (using `start.sh` script)
=> SDL and Policy Manager are restarted

**Expected result:**
- HMI re-connects to Policy Manager
- Policy Manager is able to handle `BC.OnSystemRequest`

### Summary
There was noticed a timing issue when HMI is not fast enough to connect to Policy Manager backend after ignition off/on. As
SDL starts before the Policy Manager, there might be an issue when SDL continues PTU however HMI is not connected to PM yet which causes an exception and breaks PTU sequence. Also, HMI is trying to perform PTU even if no any apps registered yet which makes no sense if PTU over internal modem is disabled.
The following changes were done:
- Postpone PTU sequence until at least one app is registered
- Resume PTU sequence once app is registered and PTU was postponed
- Postpone sending of messages to Policy Manager until socket is connected
- Resume sending of postponed messages to PM once coonection is established

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-03-24 18:52 UTC, jacobkeeler requested changes
In addition, it looks like there is a race condition in Core where OnSystemRequest will be sent from the HMI before the app has a valid HMI State. Since Core is sending OnAppRegistered before the app's state is valid, this is a Core issue. I will submit a fix soon

2021-03-24 20:10 UTC, jacobkeeler commented
See https://github.com/smartdevicelink/sdl_core/pull/3675 for the fix mentioned earlier

2021-03-24 21:13 UTC, AKalinich-Luxoft commented on app/controller/SettingsController.js
> +        this.set('nextPtuIterationScheduled', false);
@jacobkeeler good idea. Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/540/commits/f5198d46be8e0e8484e08031bd4b84c1deb25b55

2021-03-24 21:13 UTC, AKalinich-Luxoft commented on app/controller/SettingsController.js
> +      if (SDL.SDLModel.data.registeredApps.length > 0) {
@jacobkeeler is think it is redundant and can be skipped for that function as it is covered by internal one.
Removed in https://github.com/smartdevicelink/sdl_hmi/pull/540/commits/f5198d46be8e0e8484e08031bd4b84c1deb25b55

2021-03-24 21:14 UTC, AKalinich-Luxoft commented
> See [smartdevicelink/sdl_core#3675](https://github.com/smartdevicelink/sdl_core/pull/3675) for the fix mentioned earlier

@jacobkeeler thank you for noticing and fixing this race condition in Core

2021-03-25 15:50 UTC, jacobkeeler submitted a review, later dismissed

2021-03-25 20:00 UTC, jacobkeeler commented
@AKalinich-Luxoft Unfortunately it seems that [smartdevicelink/sdl_core#3675](https://github.com/smartdevicelink/sdl_core/pull/3675) causes some issues with the resumption and widgets features, and it's looking like there isn't really a clean way to fix the issue as of now. Since the resumption process needs to occur after `BC.OnAppRegistered`, it's looking like we can't guarantee that the whole registration process is complete by that time. It does look like `UpdateAppList` will be sent after the registration is complete however, so for now I believe that a decent solution would be to move this logic to occur when `BC.UpdateAppList` is received, rather than when the app list is changed.

```
...
      SDL.InfoAppsView.showAppList();

      params.applications.forEach(appRecord => {
        SDL.SDLModel.appIDtoPolicyAppIDMapping[appRecord.appID] = appRecord.policyAppID;
      });
+     SDL.SettingsController.runScheduledPtuIteration();
},
...
```

2021-03-30 15:12 UTC, jordynmackool commented
@AKalinich-Luxoft please see @jacobkeeler's [comment](https://github.com/smartdevicelink/sdl_hmi/pull/540#issuecomment-807384006) above and let us know if you plan to make the suggested update.

2021-03-30 23:54 UTC, AKalinich-Luxoft commented
> @AKalinich-Luxoft Unfortunately it seems that [smartdevicelink/sdl_core#3675](https://github.com/smartdevicelink/sdl_core/pull/3675) causes some issues with the resumption and widgets features, and it's looking like there isn't really a clean way to fix the issue as of now. Since the resumption process needs to occur after `BC.OnAppRegistered`, it's looking like we can't guarantee that the whole registration process is complete by that time. It does look like `UpdateAppList` will be sent after the registration is complete however, so for now I believe that a decent solution would be to move this logic to occur when `BC.UpdateAppList` is received, rather than when the app list is changed.
> 
> ```
> ...
>       SDL.InfoAppsView.showAppList();
> 
>       params.applications.forEach(appRecord => {
>         SDL.SDLModel.appIDtoPolicyAppIDMapping[appRecord.appID] = appRecord.policyAppID;
>       });
> +     SDL.SettingsController.runScheduledPtuIteration();
> },
> ...
> ```

@jordynmackool @jacobkeeler sorry for a late response, looks like I missed a notification about this PR.
These changes make sense to me. Implementation has been updated in https://github.com/smartdevicelink/sdl_hmi/pull/540/commits/1379e858e153fa5ac6f25ad46d0f42b7c714e400

2021-03-31 15:19 UTC, jacobkeeler commented on app/controller/SettingsController.js
> +      if (SDL.SDLModel.data.registeredApps.length > 0 && this.nextPtuIterationScheduled) {
@AKalinich-Luxoft something else that came to mind. Not all apps are going to be available for PTUs since they might not be registered (specifically, cloud apps and webengine apps will appear in the app list before they are registered). I think we might need to filter this app list accordingly. It doesn't look like you can tell if the app is registered by the contents of the `HMIApplication` struct, but you may be able to keep track of a `registered` flag which is set to true when `OnAppRegistered` and false when `OnAppUnregistered` is received.

2021-03-31 22:13 UTC, AKalinich-Luxoft commented on app/controller/SettingsController.js
> +      if (SDL.SDLModel.data.registeredApps.length > 0 && this.nextPtuIterationScheduled) {
@jacobkeeler it's a good point for sure. Actually, we already have a flag `initialized` for that purposes, implemented recently for WebEngine apps exactly by that reason. I added corresponding check in https://github.com/smartdevicelink/sdl_hmi/pull/540/commits/3151fe2d046fb4da273a5a148812f9625565f6b5
This flag will be set to false for apps which are actually not registered. Please let me know if you are ok with such solution

2021-04-01 13:15 UTC, jacobkeeler approved these changes

2021-04-01 13:15 UTC, merged