Fixed HMI does not apply Display mode to the main Alert image
smartdevicelink/sdl_hmi pull request #568
Opened 2021-05-20 12:07 UTC by Ypostolov

Fixes [#516 ](github.com/smartdevicelink/sdl_hmi/issues/516)

This PR is **ready** for review.

### Testing Plan
Mobile application is registered and activated, mobile app requests Alert( "AlertIcon" = { "value" = .png, "imageType" = "DYNAMIC", "isTemplate" = true }), than display mode changed, observe HMI applies display mode to the main Alert image.

### Summary
Fixed HMI does not apply Display mode to the main Alert image.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-08-11 20:18 UTC, ShobhitAd requested changes
Please resolve merge conflicts

2021-08-11 20:18 UTC, ShobhitAd commented on css/sdl.css
> +    height: 70px;
The ico-overlay doesn't cover the alertPopUpImage image since the ico-overlay is 80 x 70 and the alertPopUpImage has a maxwidth of 120
![Screenshot from 2021-08-11 16-16-14](https://user-images.githubusercontent.com/10703941/129097359-8a170109-b71c-4609-95aa-fca61f422914.png)

2021-08-12 17:52 UTC, jordynmackool commented
@Ypostolov please see the review feedback from Shobhit above.

2021-08-16 21:13 UTC, Ypostolov commented on css/sdl.css
> +    height: 70px;
Fixed in 73427ce926320b893aaa0d8251cc7040316b67f6

2021-08-16 21:14 UTC, Ypostolov commented
> Please resolve merge conflicts

@ShobhitAd  
resolved in a5a6985dcfcf1a7b62afa96c98dd0c9afe490b2c

2021-08-16 21:17 UTC, Ypostolov commented
> @Ypostolov please see the review feedback from Shobhit above.

@jordynmackool 
All Livio comments have been processed. Thank you!

2021-08-17 13:50 UTC, ShobhitAd approved these changes

2021-08-17 13:50 UTC, merged