Fix/Reset AudioStreamingIndicator to PLAY_PAUSE
smartdevicelink/sdl_hmi pull request #572
Opened 2021-05-24 16:38 UTC by ShobhitAd

Implements/Fixes #517

This PR is **ready** for review.

### Testing Plan
Run reproduction steps using Test Suite/RPC Builder app

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-05-27 15:28 UTC, jacobkeeler requested changes

2021-05-27 15:28 UTC, jacobkeeler commented on ffw/UIRPC.js
>                }
```suggestion
              
              var indicator = request.params.audioStreamingIndicator ? request.params.audioStreamingIndicator : "PLAY_PAUSE"
              SDL.SDLController.SetAudioStreamingIndicator(indicator)

```
Seems a bit odd to be sending in a modified version of the message. I would suggest editing the function to take in the indicator rather than the full message, as most of it is unused in the function at the moment

2021-05-27 18:12 UTC, ShobhitAd commented
@jacobkeeler Applied suggested change. Also added change to reset audioStreamingIndicator to PLAY_PAUSE when app enters HMI_NONE (as specified in the proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0109-set-audio-streaming-indicator.md#hmi--mobile-api)

2021-05-28 13:49 UTC, jacobkeeler requested changes

2021-05-28 13:49 UTC, jacobkeeler commented on ffw/UIRPC.js
>            case 'UI.SetAudioStreamingIndicator':
Looks like this might've been from before the project became open-source. This RPC does not exist. Probably best to just remove this case

2021-05-28 15:45 UTC, jacobkeeler approved these changes

2021-05-28 15:51 UTC, merged