Feature/sdl 0189 restructuring on reset timeout
smartdevicelink/sdl_hmi pull request #575
Opened 2021-06-24 15:47 UTC by LitvinenkoIra

Implements https://github.com/smartdevicelink/sdl_hmi/issues/376

This PR is **[not ready]** for review.

### Testing Plan
[0189_Restructuring OnResetTimeout_HMI_instruction.xlsx](https://github.com/smartdevicelink/sdl_hmi/files/6710538/0189_Restructuring.OnResetTimeout_HMI_instruction.xlsx)

### Summary
The ability to send OnResetTimeout for RPS with different interfaces has been added.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-06-24 19:37 UTC, atiwari9 requested changes

2021-06-24 19:37 UTC, atiwari9 commented on ffw/BasicCommunicationRPC.js
> +        if(isValidResetPeriod(resetPeriod)){
Can you please update the timer logic on HMI to reflect correct timeout as well. In case timeout value is > 1000000 ms then it is not sent to SDL. In that case the timeout is set to default timeout. Refer: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0189-Restructuring-OnResetTimeout.md#basiccommunication-onresettimeout-would-be-added

2021-06-25 11:47 UTC, ValeriiMalkov commented on ffw/BasicCommunicationRPC.js
> +        if(isValidResetPeriod(resetPeriod)){
Please take a look in commit e33899a82565f71ec96d840aefeb23ba460bec74

2021-06-25 13:30 UTC, atiwari9 approved these changes

2021-06-25 18:47 UTC, atiwari9 requested changes
More changes are needed as per this `SDL_Core` comment: https://github.com/smartdevicelink/sdl_core/pull/3726#discussion_r658891896

2021-06-28 14:29 UTC, atiwari9 commented
@ValeriiMalkov , @LitvinenkoIra  - Please let me know when the PR is ready to be reviewed again after above mentioned changes.

2021-06-28 21:42 UTC, atiwari9 approved these changes

2021-06-29 02:09 UTC, AKalinich-Luxoft commented
> @ValeriiMalkov , @LitvinenkoIra - Please let me know when the PR is ready to be reviewed again after above mentioned changes.

All required changes have been provided in https://github.com/smartdevicelink/sdl_hmi/pull/575/commits/99c82a99e37a3a3b3ed5914276d6b9157e48db8a

2021-06-29 16:31 UTC, LitvinenkoIra commented
@theresalech This PR is ready for Livio review. Thank you!

2021-07-20 13:39 UTC, iCollin requested changes

2021-07-20 13:39 UTC, iCollin commented
When UI interactions are deactivated for reason other than timeout, they must be removed from `SDL.ResetTimeoutPopUp.resetTimeoutRPCs` so that a timeout is not sent later.

2021-07-20 13:40 UTC, iCollin commented
Many components had their "timeout timers" moved to the ResetTimeoutPopup component like this:

```
SDL.ResetTimeoutPopUp.expandCallbacks(function(){
                SDL.ScrollableMessage.deactivate();
              }, request.method);
```

But many of these same components still have a "timer" that seems to be for timeout in the components themselves. These duplicate timers should be removed.

2021-07-20 13:40 UTC, iCollin commented
It will be common for apps to have multiple pending requests at the same time. The `SDL.ResetTimeoutPopUp` needs to be able to handle this, and requires a few changes:
- Remove any calls to `SDL.ResetTimeoutPopUp.DeactivatePopUp` when there are other pending messages
    - AlertManeuver does this already
- Modify `SDL.ResetTimeoutPopUp.resetTimeout` or provide another method to be able to reset the timeout of just one message.
    - Currently this method is called from both clicking `resetTimeoutButton` as well as when the timer should be reset for ScrollableMessage and Slider. At least the calls from the RPCs should be for just that one RPC's timeout.

2021-07-20 13:42 UTC, iCollin commented
I recommend consolidating the objects indexed by `[method]` on SDL.ResetTimeoutPopUp to one object of objects. Currently we are tracking the `requestIDs`, `timeoutSeconds`, `callbacks` and `resetTimeoutCallback` data like this:
```
// array resetTimeoutRPCs: [
	'UI.Alert'
]
// object 1 requestIDs: {
	'UI.Alert': 1
}
// object 2 timeoutSeconds: {
	'UI.Alert': 5
}
// object 3 callbacks: {
	'UI.Alert': () => { console.log('alert timed out'); }
}
// object 4 resetTimeoutCallback: {
	'UI.Alert': () => { console.log('alert timeout reset'); }
}
```
And it may be easier to use in code like this:
```
// object resetTimeoutRPCs: {
	1: { // key is requestID
		method: 'UI.Alert',
		timeoutSeconds: 5,
		callback: () => { console.log('alert timed out'); },
		resetTimeoutCallback: () => { console.log('alert timeout reset'); }
	}
}
```
There are two reasons:
- Easier to use in code
    - For example, right now only the `resetTimeoutRPCs` member of those 5 is cleaned up before deactivate is called.
    - Cleanup is just `delete resetTimeoutRPCs[1]` instead of modifying many objects
- Supports multiple of the same method
    - Not necessary now, but may be in the future if interactions can be sent to multiple windows etc.

2021-07-20 13:43 UTC, iCollin commented
Where applicable, it would be much easier to follow these changes if the code for setting up the timeout callbacks was placed within interaction components.

For example, I believe all the changes from `ffw/NavigationRPC.js` should be moved to the `SDL.AlertManeuverPopUp.AlertManeuverActive` method. This same pattern can be followed for other RPC file changes.

2021-07-20 13:44 UTC, iCollin commented
Please merge in develop and feel free to message me on slack if you have any questions!

2021-07-21 10:17 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +                const TIME_OUT_EXPIRATION_SECONDS = 1;
@iCollin We need to send response a bit earlier then timeout expired. If we will send after requested timeout SDL will respond to mobile with error `TIMEOUT`. That's why we send one second earlier then timeout expired

2021-07-21 10:54 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +            return
@iCollin This is Ancur's demand: https://github.com/smartdevicelink/sdl_hmi/pull/575#discussion_r658229886

2021-07-21 11:24 UTC, ValeriiMalkov commented on ffw/TTSRPC.js
> +          if (SDL.ResetTimeoutPopUp.resetTimeoutRPCs.includes(request.method)) {
@iCollin Currently all logic with TTS replaced with `SDL.ResetTimeoutPopUp`. `SDL.TTSPopUp` is deprecated.
We can check is it active by call `SDL.ResetTimeoutPopUp.resetTimeoutRPCs.includes('TTS.Speak')`

2021-07-21 11:27 UTC, ValeriiMalkov commented on ffw/TTSRPC.js
> +            }
@iCollin Not sure in this comment

2021-07-21 12:21 UTC, ValeriiMalkov commented on app/view/sdl/VRHelpListView.js
> +        SDL.ResetTimeoutPopUp.vrPerformInteractionDisableCheckBox()
@iCollin An element was removed, but checkbox is exist. It's just disabled to prevent erroneous pressing

2021-07-21 12:31 UTC, ValeriiMalkov commented on app/view/sdl/shared/AbstractView.js
> +      if(SDL.ResetTimeoutPopUp.active && this.elementId != "vr_help_list_view") {
@iCollin It is to check which part of performinteraction request deactivates. If it is not a VR part, ResetTimeoutPopUp should be deactivated

2021-07-21 13:51 UTC, iCollin commented on app/view/sdl/ResetTimeoutPopUp.js
> +            return
Okay, thank you for explaining. Please disregard similar comment on other HMI PR :)

2021-07-21 13:54 UTC, iCollin commented on ffw/TTSRPC.js
> +          if (SDL.ResetTimeoutPopUp.resetTimeoutRPCs.includes(request.method)) {
Ah understood. Then `ResetTimeoutPopUp` will have to handle sending TTS.Started and TTS.Stopped.

Can we remove TTSPopup in this PR? Will there no longer be a way to visually see the TTS after these changes?

2021-07-21 13:55 UTC, iCollin commented on ffw/TTSRPC.js
> +            }
I left this comment because it is possible for Mobile to send just TTS Speak that may not be related to any Alert or AlertManeuver so this logic shouldn't be here in the TTS Speak handler.

2021-07-21 13:58 UTC, iCollin commented on app/view/sdl/shared/AbstractView.js
> +      if(SDL.ResetTimeoutPopUp.active && this.elementId != "vr_help_list_view") {
Thank you, that helps me understand. If that is the goal, could we put the call to `SDL.ResetTimeoutPopUp.DeactivatePopUp();` inside `SDL.InteractionChoicesView.deactivate()`? I think that makes it more obvious what is causing this.

2021-07-21 14:32 UTC, ValeriiMalkov commented on app/view/sdl/shared/interactionChoicesView.js
> +        self.timeout = SDL.ResetTimeoutPopUp ? SDL.ResetTimeoutPopUp.timeoutSeconds['UI.PerformInteraction'] * 1000 : self.timeout
@iCollin There is a very specific logic for `PerformInteraction` RPC. We decide to leave this logic, beacuse this method observes some input value.

2021-07-21 14:47 UTC, ValeriiMalkov commented on app/view/sdl/shared/scrollableMessage.js
> +      clearTimeout(self.timer);
@iCollin There is a place where timer won't cleared https://github.com/smartdevicelink/sdl_hmi/blob/a7e38358239d2b462e2c0f7a63ff4cbfbd628c0d/app/controller/sdl/Abstract/Controller.js#L722

2021-07-21 14:50 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +        }
@iCollin Good point, but maybe better to leave it to prevent unexpected errors ?

2021-07-22 15:03 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> + * Copyright (c) 2018, Ford Motor Company All rights reserved.
Fixed in 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:03 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +      }, timer - 1000
@iCollin I've create a const in commit 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:04 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +      SDL.ResetTimeoutPopUp.play(files);
@iCollin Fixed in 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:04 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +        if('string' == typeof msg) {
@iCollin Fixed in 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:06 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +        }
@iCollin Agree. Fixed in 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:07 UTC, ValeriiMalkov commented on app/controller/sdl/Abstract/Controller.js
> +    messageRequestId: null,
@iCollin After analyze the code, it's unnecessary. Removed in commit 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:08 UTC, ValeriiMalkov commented on app/controller/sdl/RController.js
> +   },
@iCollin Fixed in 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:11 UTC, ValeriiMalkov commented on app/view/sdl/AlertManeuverPopUp.js
> +    },
@iCollin Looks like it's unnecessary logic in this method. I leave this method with empty implementation. Currently it's used in ResetTimeoutPopUp as a callback. Maybe we will extend this logic in a future.

2021-07-22 15:13 UTC, ValeriiMalkov commented on ffw/TTSRPC.js
> +          if (SDL.ResetTimeoutPopUp.resetTimeoutRPCs.includes(request.method)) {
@iCollin There are a places where it is used not only within a reset timeout. It takes a time for this.

2021-07-22 15:15 UTC, ValeriiMalkov commented on app/view/sdl/AlertPopUp.js
> +    },
@iCollin Replaced with empty function. Currently looks like unnecessary logic. Maybe could be extend in a future

2021-07-22 15:16 UTC, ValeriiMalkov commented on app/view/sdl/SubtleAlertPopUp.js
> -            window.removeEventListener('click', this.onClick);
@iCollin After code analyzing, logic returned in commit cf22cf9c726a593f665100ef4892b4b4b2c8dd7f

2021-07-22 15:17 UTC, ValeriiMalkov commented on app/view/sdl/SubtleAlertPopUp.js
> +        },
@iCollin The same as above https://github.com/smartdevicelink/sdl_hmi/pull/575#discussion_r674906428

2021-07-22 15:18 UTC, ValeriiMalkov commented on app/view/sdl/shared/interactionChoicesView.js
> +          SDL.SDLModel.uiShowKeyboard(this, this.requestID);
@iCollin Removed and tested 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:20 UTC, ValeriiMalkov commented on app/view/sdl/shared/interactionChoicesView.js
> +      self = SDL.InteractionChoicesView === undefined ? this : SDL.InteractionChoicesView;
@iCollin Actually it's needed. When HMI is starting, this method will called and SDL.InteractionChoicesView isn't initialized and not defined. Replaced with `Nullish coalescing operator(??)` in commit 42363147989c350431f43aa8498463bf8f9afa48.

2021-07-22 15:22 UTC, ValeriiMalkov commented on app/controller/sdl/Abstract/Controller.js
> -          this.onResetTimeout(element.appID, 'UI.Alert');
@iCollin Fixed in 42363147989c350431f43aa8498463bf8f9afa48

2021-07-22 15:33 UTC, ValeriiMalkov commented
> I recommend consolidating the objects indexed by `[method]` on SDL.ResetTimeoutPopUp to one object of objects. Currently we are tracking the `requestIDs`, `timeoutSeconds`, `callbacks` and `resetTimeoutCallback` data like this:
> 
> ```
> // array resetTimeoutRPCs: [
> 	'UI.Alert'
> ]
> // object 1 requestIDs: {
> 	'UI.Alert': 1
> }
> // object 2 timeoutSeconds: {
> 	'UI.Alert': 5
> }
> // object 3 callbacks: {
> 	'UI.Alert': () => { console.log('alert timed out'); }
> }
> // object 4 resetTimeoutCallback: {
> 	'UI.Alert': () => { console.log('alert timeout reset'); }
> }
> ```
> 
> And it may be easier to use in code like this:
> 
> ```
> // object resetTimeoutRPCs: {
> 	1: { // key is requestID
> 		method: 'UI.Alert',
> 		timeoutSeconds: 5,
> 		callback: () => { console.log('alert timed out'); },
> 		resetTimeoutCallback: () => { console.log('alert timeout reset'); }
> 	}
> }
> ```
> 
> There are two reasons:
> 
> * Easier to use in code
>   
>   * For example, right now only the `resetTimeoutRPCs` member of those 5 is cleaned up before deactivate is called.
>   * Cleanup is just `delete resetTimeoutRPCs[1]` instead of modifying many objects
> * Supports multiple of the same method
>   
>   * Not necessary now, but may be in the future if interactions can be sent to multiple windows etc.

Note that this is a significant refactoring and it will require a full testing cycle. 
According to our estimates we will be able to deliver these changes by the end of next week (07.30). Are you ok with that?

2021-07-22 15:35 UTC, iCollin commented
> Note that this is a significant refactoring and it will require a full testing cycle.
According to our estimates we will be able to deliver these changes by the end of next week (07.30). Are you ok with that?

It is a bigger refactor, but I think it will make cleanup of the variables simpler and make it easier to use them going forward. I am fine with the end of next week :+1:

2021-07-22 17:35 UTC, iCollin commented on app/model/sdl/Abstract/Model.js
> +  deactivateVr: function() {
```suggestion
  deactivateVrInteraction: function() {
```

2021-07-22 17:35 UTC, iCollin commented on app/model/sdl/Abstract/Model.js
> +  vrTimeout: function(timer) {
```suggestion
  vrInteractionTimeout: function(timer) {
```

2021-07-22 17:35 UTC, iCollin commented on app/model/sdl/Abstract/Model.js
> +      }, timer - 1000
Where timeout is specified by user we should not modify the timeout.

2021-07-22 17:40 UTC, iCollin commented on app/view/sdl/AlertManeuverPopUp.js
> +    },
I see. I can't think of anything we will use this for in the future... Can you? If not I think we should remove it.

2021-07-22 17:46 UTC, iCollin commented on app/view/sdl/ResetTimeoutPopUp.js
> +        }
```
if (null !== resetTimeoutRPCs) {
    this.resetTimeoutRPCs = this.resetTimeoutRPCs.concat(resetTimeoutRPCs);
}
```

Yeah that's fine, but then can we do like this? My main concern was that we don't need to call `.concat` with an empty array

2021-07-22 17:49 UTC, iCollin commented on app/controller/sdl/Abstract/Controller.js
> -          this.onResetTimeout(element.appID, 'UI.Alert');
We can remove the switch here as well, but this looks better. I think we'd want to just reset the timeout of one RPC here though, the one which clicked Keep Context. For instance if an unrelated TTS Speak is going on, we shouldn't reset that timeout.

2021-07-22 18:33 UTC, iCollin commented on ffw/TTSRPC.js
> +          if (SDL.ResetTimeoutPopUp.resetTimeoutRPCs.includes(request.method)) {
I am concerned about having two TTS modules though, what will happen if Core receives TTS Started while TTS is already going? How will we check in code if any TTS is active, would we need to check both?

2021-07-28 21:11 UTC, iCollin reviewed
All comments above here have been addressed.

I have left [a comment on the Core PR](https://github.com/smartdevicelink/sdl_core/pull/3726#issuecomment-888553791) to alleviate issues with timeouts arriving after Core has sent a generic error, we should be able to remove the `timeout - 1000` modifications once that is addressed.

2021-07-28 21:11 UTC, iCollin commented on ffw/UIRPC.js
> -              SDL.SDLController.onSystemContextChange(request.params.appID);
We should still fire `onSystemContextChange` when an alert is activated (and same for subtle alert)

2021-07-28 21:11 UTC, iCollin commented on ffw/UIRPC.js
> +                SDL.ResetTimeoutPopUp.setTimeoutByRpcName(method, timeout);
I think it will be easier to follow if we apply the timeouts in the addRpc calls for both PerformInteraction RPCs

2021-07-28 21:11 UTC, iCollin commented on ffw/UIRPC.js
> +
Can this please be moved inside uiSlider()?

2021-07-28 21:11 UTC, iCollin commented on ffw/UIRPC.js
> +              SDL.ResetTimeoutPopUp.ActivatePopUp();
Can this please be moved inside `onSDLScrolableMessage`?

2021-07-28 21:11 UTC, iCollin commented on ffw/TTSRPC.js
> +          if (SDL.ResetTimeoutPopUp.includes(request.method) || rejectCallbacks.length > 0) {
Now that we have two TTS components, we need to check both of them to make sure no TTS is being used.

```
SDL.ResetTimeoutPopUp.includes('TTS.Speak') || SDL.TTSPopUp.active
```

I suggest we make a common method for this check since it will be in many places. If we do not check both, The HMI may be speaking a GetUserFriendlyMessage when this RPC comes in.

2021-07-29 08:03 UTC, ValeriiMalkov commented on app/view/sdl/AlertManeuverPopUp.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('TTS.Speak', true);
@iCollin Seems there is no way to check. If the TTS currently active, other TTS reqeusts will be rejected. For instance if we send Alert with TTS then Speak from mobil, Speak will be rejected by HMI.

2021-07-29 08:26 UTC, ValeriiMalkov commented on app/view/sdl/AlertManeuverPopUp.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('TTS.Speak', true);
@iCollin Actually the module is busy and seems it is normal that it is rejected, and only one TTS could be active.
One note: There is same behavior on the develop branch. It is not in the feature scope.

2021-07-29 15:01 UTC, ValeriiMalkov commented on app/controller/sdl/Abstract/Controller.js
> +          SDL.ResetTimeoutPopUp.resetTimeout();
@iCollin Fixed ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:01 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +                this.set('timeoutString', message);
@iCollin Fixed ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:01 UTC, ValeriiMalkov commented on app/controller/sdl/Abstract/Controller.js
> +      // SDL.ResetTimeoutPopUp.stopRpcProcessing(methodName);
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:01 UTC, ValeriiMalkov commented on app/controller/sdl/KeyboardController.js
> +            );
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:01 UTC, ValeriiMalkov commented on app/controller/sdl/RController.js
> +            if(SDL.ResetTimeoutPopUp.active) {
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:01 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +  timeout: null,
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +    SDL.ResetTimeoutPopUp.timeoutSeconds = defaultTimeout;
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +      SDL.ResetTimeoutPopUp.stopRpcProcessing('TTS.Speak');
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/view/sdl/AlertPopUp.js
> +    ttsTimeout: null,
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/view/sdl/SubtleAlertPopUp.js
> +        ttsTimeout: null,
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/view/sdl/SubtleAlertPopUp.js
> +                SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.SubtleAlert', true);
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/view/sdl/shared/interactionChoicesView.js
> +            FFW.BasicCommunication.OnResetTimeout(
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/view/sdl/shared/interactionChoicesView.js
> +            FFW.BasicCommunication.OnResetTimeout(
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:02 UTC, ValeriiMalkov commented on app/view/sdl/shared/scrollableMessage.js
> +          if(SDL.ResetTimeoutPopUp.includes('UI.ScrollableMessage')) SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage');
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on app/view/sdl/shared/scrollableMessage.js
> +          SDL.ResetTimeoutPopUp.resetTimeout();
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on app/view/sdl/shared/sliderView.js
> +        if(SDL.ResetTimeoutPopUp.includes('UI.Slider')) SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.Slider');
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on app/view/sdl/shared/sliderView.js
> +          SDL.ResetTimeoutPopUp.DeactivatePopUp();
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on ffw/BasicCommunicationRPC.js
> +        }
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +              }
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> -              SDL.SDLController.onSystemContextChange(request.params.appID);
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +                SDL.ResetTimeoutPopUp.setTimeoutByRpcName(method, timeout);
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +              SDL.ResetTimeoutPopUp.ActivatePopUp();
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 15:03 UTC, ValeriiMalkov commented on ffw/TTSRPC.js
> +          if (SDL.ResetTimeoutPopUp.includes(request.method) || rejectCallbacks.length > 0) {
@iCollin Updated ab84539480f9705baa077afab0bc8aca3521e5ba

2021-07-29 16:42 UTC, iCollin commented on app/controller/sdl/Abstract/Controller.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage', true);
Why don't we call deactivate here?

2021-07-29 16:42 UTC, iCollin commented on app/view/sdl/ResetTimeoutPopUp.js
> -                this.set('timeoutString', message);
with this removed, `message` is unused, can we remove that variable?

2021-07-29 16:42 UTC, iCollin commented on app/model/sdl/Abstract/Model.js
> +      }
Sorry, previous comment was naive.

This block should really go inside AlertActive so it is run every time the alert is activated.

Right now the call when it takes over priority from another alert won't have a timeout timer.

2021-07-29 16:42 UTC, iCollin commented on app/model/sdl/Abstract/Model.js
> +      }
this block should be moved into `SubtleAlertActive`

2021-07-29 16:42 UTC, iCollin commented on ffw/UIRPC.js
> +            SDL.SDLController.onSystemContextChange(request.params.appID);
```suggestion
            if (SDL.SDLModel.onUIAlert(request)) {
                SDL.SDLController.onSystemContextChange(request.params.appID);
            }
```

2021-07-29 16:47 UTC, iCollin reviewed
There is one comment above that I think was missed: https://github.com/smartdevicelink/sdl_hmi/pull/575#discussion_r678642901

2021-07-29 16:47 UTC, iCollin commented on ffw/UIRPC.js
> +              SDL.ScrollableMessage.deactivate('ABORTED');
```suggestion
              SDL.ScrollableMessage.deactivate(true);
```

this parameter is a boolean

2021-07-29 16:47 UTC, iCollin commented on ffw/UIRPC.js
> +                timeout *= INCREASE_UI_TIMEOUT;
The HMI shouldn't be adjusting incoming timeouts, I think we should pass timeout as it comes to addRpc.

2021-07-29 16:51 UTC, iCollin commented on app/view/sdl/AlertManeuverPopUp.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('TTS.Speak', true);
```suggestion
          SDL.SDLController.TTSResponseHandler();
```

2021-07-29 16:53 UTC, iCollin commented on app/view/sdl/AlertManeuverPopUp.js
> +      if(!message) {
Do we need to check `!message`? This will always be true, maybe we can just remove the parameter from this method?

2021-07-29 18:03 UTC, iCollin commented on app/model/sdl/Abstract/Model.js
> +      if(!message.params.softButtons){
Before this PR, Alert would always timeout. I don't see any reason why it shouldn't timeout in the proposal.

before it was timing out in `message.duration ?? 30000`ms

2021-07-30 07:07 UTC, ValeriiMalkov commented on app/controller/sdl/Abstract/Controller.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage', true);
@iCollin Beacuse there is no timeout reason in method arguments. `ResetTimeoutPopUp` won't be called from `deactivate` method

2021-07-30 07:58 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +                timeout *= INCREASE_UI_TIMEOUT;
@iCollin The timer for UI part starts after receiving response for VR part. Do you have other solution for this ?

2021-07-30 12:26 UTC, iCollin commented on app/controller/sdl/Abstract/Controller.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage', true);
Thank you, that explains why we call `stopRpcProcessing` but here we also need to call deactivate() so that ScrollableMessage will get a reply when we click steal focus.

2021-07-30 12:28 UTC, ValeriiMalkov commented on app/view/sdl/shared/scrollableMessage.js
> +          if(SDL.ResetTimeoutPopUp.includes('UI.ScrollableMessage')) SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage');
@iCollin In case if aborted true, it means that it is timeout reason. How to move it outside `calculate_result_code` method?
Adding additional condition?

2021-07-30 12:33 UTC, iCollin commented on app/controller/sdl/Abstract/Controller.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage', true);
```suggestion
          SDL.ScrollableMessage.deactivate();
```

It has argument ABORTED which means timeout. Here we need to reply to ScrollableMessage.

2021-07-30 12:34 UTC, iCollin commented on app/view/sdl/shared/scrollableMessage.js
> +          if(SDL.ResetTimeoutPopUp.includes('UI.ScrollableMessage')) SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage');
We need to call `SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage');` when reason is anything besides timeout.

2021-07-30 12:36 UTC, iCollin commented on app/view/sdl/shared/scrollableMessage.js
> +          if(SDL.ResetTimeoutPopUp.includes('UI.ScrollableMessage')) SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage');
Good point, it is fine in `calculate_result_code` but should be in the opposite cases.

2021-07-30 12:43 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +                timeout *= INCREASE_UI_TIMEOUT;
@iCollin Agree with comment. It should be starts after VR part response. Implemented in commit e8870be9de26a43dd738e094c0a6240881743eba

2021-07-30 12:43 UTC, ValeriiMalkov commented on app/view/sdl/AlertManeuverPopUp.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('TTS.Speak', true);
@iCollin Fixed 054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:45 UTC, ValeriiMalkov commented on app/view/sdl/AlertManeuverPopUp.js
> +      if(!message) {
@iCollin Needs to check is it timeout reason or not. Renamed to timeout for more readable 054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:45 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +      if(!message.params.softButtons){
Fixed in 054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:46 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +              SDL.ScrollableMessage.deactivate('ABORTED');
Fixed 054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:46 UTC, ValeriiMalkov commented on ffw/UIRPC.js
> +            SDL.SDLController.onSystemContextChange(request.params.appID);
Fixed 054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:46 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +      }
Fixed 054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:46 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +      }
054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:46 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> -                this.set('timeoutString', message);
Fixed 054eed300ffaa868debb193381f640baefd9a733

2021-07-30 12:52 UTC, ValeriiMalkov commented on app/view/sdl/shared/scrollableMessage.js
> +          if(SDL.ResetTimeoutPopUp.includes('UI.ScrollableMessage')) SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage');
Fixed b7ddd991ead5c5f706f746327241cf92acf5e828

2021-07-30 12:52 UTC, ValeriiMalkov commented on app/controller/sdl/Abstract/Controller.js
> +          SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage', true);
Fixed in  ccdec68de9a6be27d491716d7e87e411a7139544

2021-07-30 14:37 UTC, iCollin commented on app/view/sdl/shared/scrollableMessage.js
> +          if(SDL.ResetTimeoutPopUp.includes('UI.ScrollableMessage')) SDL.ResetTimeoutPopUp.stopRpcProcessing('UI.ScrollableMessage');
I see now, every call besides timeout is aborted lol.

2021-07-30 14:50 UTC, iCollin reviewed
Updates look great, thank you for the quick responses.

2021-07-30 14:50 UTC, iCollin commented on app/view/sdl/ResetTimeoutPopUp.js
> +                if(TIME_OUT_EXPIRATION_SECONDS === this.resetTimeoutRPCs[requestID].timeoutSeconds) {
This is checked when the key is added to `timeoutExpired`, i think this check is redundant.

2021-08-02 08:18 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +                if(TIME_OUT_EXPIRATION_SECONDS === this.resetTimeoutRPCs[requestID].timeoutSeconds) {
@iCollin Agree 0f733e6

2021-08-02 08:20 UTC, ValeriiMalkov commented
@iCollin Implemented [according a comment](https://github.com/smartdevicelink/sdl_core/pull/3726#issuecomment-890086527) in commit e9d199d

2021-08-03 16:52 UTC, iCollin commented
It seems resetting the timeout for `DialNumber` was missed, but it was mentioned explicitly in the proposal.
This currently works because Core [enforces no timeout](https://github.com/smartdevicelink/sdl_core/blob/develop/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/dial_number_request.cc#L63) for this RPC.

2021-08-03 16:52 UTC, iCollin commented
If an app sends a ScrollableMessage with a timeout of 50000ms, and then clicks the scroll bar to scroll down after say 10 seconds, the SDL HMI will send an OnResetTimeout(resetPeriod=10000ms), essentially now shortening the timeout of the ScrollableMessage to 20000ms.
Previously the timeout would have been reset to the original value. This is also the case with PerformInteraction, and with Slider when the data is changed.
I think the `resetPeriod` we send needs to be the original timeout value to preserve the timeout functionality.

2021-08-04 08:19 UTC, ValeriiMalkov commented
> If an app sends a ScrollableMessage with a timeout of 50000ms, and then clicks the scroll bar to scroll down after say 10 seconds, the SDL HMI will send an OnResetTimeout(resetPeriod=10000ms), essentially now shortening the timeout of the ScrollableMessage to 20000ms.
> Previously the timeout would have been reset to the original value. This is also the case with PerformInteraction, and with Slider when the data is changed.
> I think the `resetPeriod` we send needs to be the original timeout value to preserve the timeout functionality.
> 
> To solve this we could add a line like this to the object created in `addRpc`:
> 
> ```
> originalTimeout: timeoutSeconds
> ```
> 
> And then check for this value when resetting the timeout.

@iCollin Implemented in commit https://github.com/smartdevicelink/generic_hmi/pull/411#discussion_r681950194
Please take a look changes

2021-08-06 15:06 UTC, iCollin commented
> @iCollin Implemented in commit 22d6fb1

These changes need to also be applied to `resetTimeoutSpecificRpc`

2021-08-09 08:12 UTC, ValeriiMalkov commented
> > @iCollin Implemented in commit [22d6fb1](https://github.com/smartdevicelink/sdl_hmi/commit/22d6fb19f48f04bb10724fbabee16d91a9453f9e)
> 
> These changes need to also be applied to `resetTimeoutSpecificRpc`

@iCollin Applied 10efb8bb755fe04abad939b53796bd6653c309cc

2021-08-09 19:48 UTC, iCollin commented
@ValeriiMalkov Keep context soft buttons are not resetting the timeout. Cases for some UI Components need to be re-added to `keepContextSoftButton` in `app/controller/sdl/Abstract/Controller.js`

2021-08-10 08:48 UTC, ValeriiMalkov commented
> @ValeriiMalkov Keep context soft buttons are not resetting the timeout. Cases for some UI Components need to be re-added to `keepContextSoftButton` in `app/controller/sdl/Abstract/Controller.js`

@iCollin Added for Alert and SubtleAlert cf12e812ed2ba64236afa3359df7cf96b752d0a9

2021-08-10 13:40 UTC, iCollin commented on app/view/sdl/SubtleAlertPopUp.js
> +                message.params.duration || this.defaultTimeout
previously default value was 10000, now it is 30000. Can we please change it back to 10000

2021-08-10 13:40 UTC, iCollin commented on app/view/sdl/SubtleAlertPopUp.js
> +            this.set('endTime', Date.now() + message.params.duration);
this needs to use `duration || defaultTimeout` (10000 ms)

2021-08-10 13:52 UTC, iCollin commented on app/model/sdl/Abstract/Model.js
> +
```suggestion
```

2021-08-10 13:52 UTC, iCollin commented on app/view/sdl/ResetTimeoutPopUp.js
> +                if (TIME_OUT_EXPIRATION_SECONDS === value.timeoutSeconds) {
```suggestion
                if (TIME_OUT_EXPIRATION_SECONDS >= value.timeoutSeconds) {
```

it cannot be assumed that all timeouts will be even seconds.

I am concerned this is major issue with the implementation. How can we make this timer more granular?

If we just make the change I suggest here, and app sends request with timeout = 9001, timeout callback won't be called for 10000ms, meaning there is high chance Core might not receive this response before sending GENERIC_ERROR.

2021-08-10 14:01 UTC, ValeriiMalkov commented on app/view/sdl/SubtleAlertPopUp.js
> +                message.params.duration || this.defaultTimeout
Fixed 1b136f9

2021-08-10 14:01 UTC, ValeriiMalkov commented on app/view/sdl/SubtleAlertPopUp.js
> +            this.set('endTime', Date.now() + message.params.duration);
Fixed 1b136f9

2021-08-10 14:01 UTC, ValeriiMalkov commented on app/model/sdl/Abstract/Model.js
> +
Fixed 1b136f9

2021-08-10 16:53 UTC, ValeriiMalkov commented on app/view/sdl/ResetTimeoutPopUp.js
> +                if (TIME_OUT_EXPIRATION_SECONDS === value.timeoutSeconds) {
Done 89c9273c47dbf5941dd4855ccf01e3809b020348

2021-08-10 19:55 UTC, iCollin approved these changes

2021-08-11 16:56 UTC, merged