Feature/sdl 0264 separating the change of audible status and the change of hmi status
smartdevicelink/sdl_hmi pull request #576
Opened 2021-07-09 08:57 UTC by Akihiro-Miyazaki

Implements/Fixes [#275](github.com/smartdevicelink/sdl_hmi/issues/275)

This PR is **[ready / not ready]** for review.

### Testing Plan
This change will be tested with sdl_core 7.0 + PR at [smartdevicelink/sdl_core#3634](https://github.com/smartdevicelink/sdl_core/pull/3634).

### Summary
This is a response to changes made by SDL 0264 and #499 .
When sending OnEventChanged (PHONE_CALL, true / false), OnAppDeactivated / OnAppActivated is sent to the app which HMI Level is FULL.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-07-12 02:59 UTC, Akihiro-Miyazaki commented
@jordynmackool -san,
This PR is ready review.
If you have no problem about this PR, please close #499. 
Thank you.

@jacobkeeler -san,
We are still waiting for your response about [our comment](https://github.com/smartdevicelink/sdl_hmi/pull/499#issuecomment-876191942).

2021-07-13 17:41 UTC, jacobkeeler commented
Moving my review comments from #499 

Ah, I can see how this case would make sense. It does get a bit more complicated if you leave the phone screen before ending the call though:

Music app screen - (phone call) -> Phone call screen -> App list - (activate nav app) -> Navigation app screen -> Phone call screen - (phone call ends) -> Music app screen?

Perhaps we should clear `redisplayAppID` if the user leaves the phone call screen?

2021-07-13 17:42 UTC, jacobkeeler requested changes

2021-07-13 17:42 UTC, jacobkeeler commented on app/controller/sdl/Abstract/Controller.js
> +          }
```suggestion
          if (SDL.SDLController.model) {
             SDL.SDLModel.data.redisplayAppID = SDL.SDLController.model.appID;
             FFW.BasicCommunication.OnAppDeactivated(SDL.SDLModel.data.redisplayAppID);
          }
```
`AppModel.level` isn't really maintained perfectly as far as I can tell, so it probably isn't a reliable way of finding the active app. A much easier way to do this would be to check `SDL.SDLController.model`, since it is keeps a copy of the active app model when available.

2021-07-13 17:42 UTC, jacobkeeler commented on app/model/sdl/Abstract/data.js
> +    redisplayAppID: null,
Perhaps this should be included in `PhoneModel.js` instead?

2021-07-14 18:40 UTC, jordynmackool commented
@Akihiro-Miyazaki please see Jacobs's review feedback above and let us know if you have any questions.

2021-07-15 01:56 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you for your comment.

> Ah, I can see how this case would make sense. It does get a bit more complicated if you leave the phone screen before ending the call though:
> 
> Music app screen - (phone call) -> Phone call screen -> App list - (activate nav app) -> Navigation app screen -> Phone call screen - (phone call ends) -> Music app screen?

We think that your recognition is wrong.
Our proposal is to return the last mode when phone call is ended.
Last mode means screen, audiostreaming, and videostreaming.
Thus, In this situation, the last screen is Navigation app screen.
Thank you.

2021-07-15 18:43 UTC, jacobkeeler commented
@Akihiro-Miyazaki Ah, I was pointing out that the current behavior of this PR is to go back to the media app screen in that scenario (since that would be the app stored in `redisplayAppId`), not that this should be the behavior.

Personally, I would not suggest just going to the last active screen when the phone call ends, I feel like that would be unexpected behavior if the user switched between several screens during the phone call. I will agree that it makes sense to go back to the original app screen if the user never leave the phone screen during the phone call, but otherwise I think we should just stay on the app screen.

1. Music screen - (phone call) -> Phone call screen - (phone call is ends) -> Music screen
2. Music app screen - (phone call) -> Phone call screen -> App list - (activate nav app) -> Navigation app screen -> Phone call screen - (phone call ends) -> Stay on phone call screen
3. Music app screen - (phone call) -> Phone call screen -> Climate screen -> Phone call screen - (phone call ends) -> Stay on phone call screen

Implementation-wise, this would just involve clearing out `redisplayAppId` if the user switches screens manually.

2021-07-16 07:47 UTC, Akihiro-Miyazaki commented on app/model/sdl/Abstract/data.js
> +    redisplayAppID: null,
@jacobkeeler -san,
Sorry for late response.
We are confirming now.
Please wait.

2021-07-16 07:47 UTC, Akihiro-Miyazaki commented on app/controller/sdl/Abstract/Controller.js
> +          }
@jacobkeeler -san,
Sorry for late response.
We are confirming now.
Please wait.

2021-07-16 08:02 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you for your description.
We can easily understand your suggestion.
We should consider..

2021-07-20 07:45 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
We are still confirming about the change the program code according to your suggestion. 

> Personally, I would not suggest just going to the last active screen when the phone call ends, I feel like that would be unexpected behavior if the user switched between several screens during the phone call. I will agree that it makes sense to go back to the original app screen if the user never leave the phone screen during the phone call, but otherwise I think we should just stay on the app screen.

Music screen - (phone call) -> Phone call screen - (phone call ends) -> Music screen
Music app screen - (phone call) -> Phone call screen -> App list - (activate nav app) -> Navigation app screen -> Phone call screen - (phone call ends) -> Stay on phone call screen
Music app screen - (phone call) -> Phone call screen -> Climate screen -> Phone call screen - (phone call ends) -> Stay on phone call screen

We are very sorry for our misunderstand.
Our proposal is to change only Audible status and to keep the screen as it is.
Therefore, we think your says are correct about the screen after phone call ends.

2021-07-20 18:42 UTC, jacobkeeler commented
@Akihiro-Miyazaki Ah, just to make sure I understand correctly, you're saying that the behavior in the examples I provided is correct? Or are you saying we should stay in the phone screen in all of these cases?

Also, my understanding is that you are still working on implementing these changes, please let us know if you need any more clarification on the desired HMI behavior.

2021-07-21 03:00 UTC, Akihiro-Miyazaki commented on app/model/sdl/Abstract/data.js
> +    redisplayAppID: null,
@jacobkeeler -san,
We confirmed it.
If we modify this according to your suggestion, we assume that [your comment](https://github.com/smartdevicelink/sdl_hmi/pull/576#discussion_r668980345) also should be modified to be able to access the PhoneModel.js file.
If our recognition is correct and there is no different behaivor between ourimplementation and your suggestion, we would like to select current one.
Is it possible?
If need to modify the hmi_state.cc file, could you please teach us how to change?
Thank you.

2021-07-21 04:33 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
We think that the behavior in the examples I provided is current behavior.
Is it correct?

2021-07-21 19:34 UTC, jacobkeeler commented on app/model/sdl/Abstract/data.js
> +    redisplayAppID: null,
@Akihiro-Miyazaki I was suggesting this change for design reasons, I am aware the behavior would be the same. It seems to me that this would be better placed in `PhoneModel.js` since it specifically relates to the phone call state, please let me know if you have reasons that it should be left as-is.

As for `hmi_state.cc`, no changes should be needed to the Core PR at this point, it has already been approved.

2021-07-21 19:38 UTC, jacobkeeler commented
@Akihiro-Miyazaki Could you point to the specific comment with the examples your referring to? It seems I'm a bit confused at this point.

2021-07-26 04:56 UTC, Akihiro-Miyazaki commented on app/model/sdl/Abstract/data.js
> +    redisplayAppID: null,
@jacobkeeler -san,
Thank you for your reply and sorry for late response.
We understood the hmi_state.cc was approved and this file do not need to change.
We will modify two files and make a commit them.
Could you please confirm them.
Thank you.

2021-07-26 06:00 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Sorry for your confuse.
The important thing is to change only audible status  at the case of phone call.
Others, such as display-screen or video streaming status, are as it is.
Thank you.

2021-07-26 18:39 UTC, jacobkeeler commented
@Akihiro-Miyazaki Ah, so you're saying that we shouldn't be changing the screen automatically at all, and the new behavior should be to stay on the app screen if `DialNumber` is sent? In that case we would remove all of the current changes in this PR and just change this section of `BasicCommunicationRPC.js`:

```
                  FFW.BasicCommunication.sendBCResult(
                    SDL.SDLModel.data.resultCode.SUCCESS,
                    request.id,
                    request.method
                  );
-                 SDL.SDLModel.onDeactivateApp('call', request.params.appID);
-                 SDL.States.goToStates('phone.dialpad');
                  SDL.PhoneController.incomingCall(request);
```

Please let me know if my understanding is correct. If so, I would consider this a reasonable solution, since it avoids any complicated issues with screen switching.

2021-07-28 08:12 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you for your suggestion and sorry for late response.
We are still confirming about your suggestion.
Just in case, please let us know the DialNumber and the PhoneCall are same event?
Our understanding is that the DialNumber is for making a call, and the PhoneCall is for receiving a call.
If our understanding is wrong, please let us know the details.
Thank you.

2021-07-28 15:46 UTC, jacobkeeler commented
@Akihiro-Miyazaki so, the phone call event can be triggered two ways:
1. Manually, via starting the call in the HMI in the phone screen.
2. Sending DialNumber from an app. This currently causes the HMI to leave the current screen and open the phone screen.

Both of these cause `OnEventChanged(PHONE_CALL, active=true)` to be sent from the HMI, starting the event.

Ending the call can only be done manually on the phone screen, this causes `OnEventChanged(PHONE_CALL, active=false)` to be sent from the HMI, ending the event.

- The current behavior when DialNumber is sent on develop is to leave the app screen and open the phone screen. The HMI will stay on the phone screen when the call is ended.
- In this PR currently, the phone screen is still opened when DialNumber is sent, but the HMI will return to the app screen when the phone call is ended.
- The behavior I was describing in [this comment](https://github.com/smartdevicelink/sdl_hmi/pull/576#issuecomment-886936532) was to stay on the app screen when DialNumber is sent and stay on the phone screen when the phone call is ended.

2021-07-29 01:51 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you for your description.
We understood the current behavior of the phone call.
As you know, the behavior of phone call end is out of scope for our proposal. 
In our proposal, we mentioned following.

> As a specific example, there is a specification that allows a user to display and receive an incoming call with Notification, Overlay or ONS without changing to the telephone screen when an incoming call is received. 
In this case, since there is no appropriate API to notify the Audible status independently, using OnEventChanged (PHONE_CALL) displays Music App on the screen, but the HMI Level becomes Background.
As a response method, we propose to avoid the problem by clearly separating the change of Audible status and the change of HMI Status.

We proposed this solution to resolve such a situation.
Therefore, we think this change is needed.
If our thought is wrong, could you please let us know the details.
Thank you.

2021-07-29 14:54 UTC, jacobkeeler commented
@Akihiro-Miyazaki I don't think it's strictly necessary to change this behavior, since it really should be a design choice for the HMI whether or not it wants to switch screens in this case. That said, if you want to replicate the behavior you quoted in the proposal
> As a specific example, there is a specification that allows a user to display and receive an incoming call with Notification, Overlay or ONS without changing to the telephone screen when an incoming call is received.
In this case, since there is no appropriate API to notify the Audible status independently, using OnEventChanged (PHONE_CALL) displays Music App on the screen, but the HMI Level becomes Background.
As a response method, we propose to avoid the problem by clearly separating the change of Audible status and the change of HMI Status.

then I think that the changes in [this comment](https://github.com/smartdevicelink/sdl_hmi/pull/576#issuecomment-886936532) should accomplish this.

2021-07-30 06:53 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you so much for your comment.
Does [Your comment](https://github.com/smartdevicelink/sdl_hmi/pull/576#issuecomment-886936532) mean a way to prevent screen transition when making a call?
ee think we do not want to prevent screen transition under any conditions.
Does your suggestion match our thought?

By the way, could you please let us know what the conditions are for "incoming call is received by displaying that the call was received by Notification, Overlay or ONS without transitioning to the phone screen"? 

Thank you.

2021-08-03 14:56 UTC, jacobkeeler commented
@Akihiro-Miyazaki 

> Does Your comment mean a way to prevent screen transition when making a call?

Specifically, it would make it so that the HMI does not automatically transition to the phone call screen when an app starts a phone call via DialNumber. It would not prevent the user from transitioning manually to the phone call screen, it just wouldn't happen automatically.

> By the way, could you please let us know what conditions are for "incoming call is received by displaying that the call is received by Notification, Overlay or ONS without transitioning to the phone screen"?

I interpreted this as just stating that the HMI should be able to stay on the current screen when a phone call is started via a notification/popup. I don't think that this exact example flow is implemented in the HMI, but I think that the closest thing is the DialNumber flow, since the HMI will display a popup to the user before starting the call.

2021-08-04 08:46 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you for your reply.
We could understand.

> Specifically, it would make it so that the HMI does not automatically transition to the phone call screen when an app starts a phone call via DialNumber. It would not prevent the user from transitioning manually to the phone call screen, it just wouldn't happen automatically.

Our thought is below.
If Media app or Navigation app is full (Audio status is Audible), system should not move to phone call screen.
If Information app is full (Audio status is Not_audible), system should move to phone call screen.

If your suggestion matches our thought above, we will modify and make a commit.

2021-08-04 19:54 UTC, jacobkeeler commented
@Akihiro-Miyazaki 

> If Media app or Navigation app is full (Audio status is Audible), system should not move to phone call screen.
> If Information app is full (Audio status is Not_audible), system should move to phone call screen.

Hmmm, this behavior seems a bit odd to me, since each of the apps would still lose audio focus because of the phone call event. In both cases, the app's audio state would change to "NOT_AUDIBLE". It would seem a bit odd that an audio app would stay in focus when it no longer has access to audio. Could you elaborate a bit on why you think this is the correct behavior?

2021-08-05 06:10 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
We describe a specific example on this proposal below.

> As a specific example, there is a specification that allows a user to display and receive an incoming call with Notification, Overlay or ONS without changing to the telephone screen when an incoming call is received.
In this case, since there is no appropriate API to notify the Audible status independently, using OnEventChanged (PHONE_CALL) displays Music App on the screen, but the HMI Level becomes Background.

We hope this information is helpful for your understanding.
Thank you.

2021-08-05 15:40 UTC, jacobkeeler commented
@Akihiro-Miyazaki 

> If Media app or Navigation app is full (Audio status is Audible), system should not move to phone call screen.
> If Information app is full (Audio status is Not_audible), system should move to phone call screen.

I don't think this behavior follows from the proposal example.

> As a specific example, there is a specification that allows a user to display and receive an incoming call with Notification, Overlay or ONS without changing to the telephone screen when an incoming call is received.
> In this case, since there is no appropriate API to notify the Audible status independently, using OnEventChanged (PHONE_CALL) displays Music App on the screen, but the HMI Level becomes Background.

The example in the proposal is just stating that it should be **possible** to stay on the app screen when a phone call is started. The app type should not matter in this case, the proposal just happens to be using a media app in the example. If anything, I would think that the HMI would stay on the app screen for an app which was `NOT_AUDIBLE` (since it doesn't use audio anyway), or (more likely) that it would treat all app types the same way.

2021-08-06 07:07 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Example is below.
![Navigation Screen](https://user-images.githubusercontent.com/60722633/128466711-16e90657-2ab6-46cf-a1b2-9ab84e500027.PNG)
<Phone call>
![Navi and Phone call](https://user-images.githubusercontent.com/60722633/128466780-6e067968-2b34-447d-8d98-d312c4efa707.PNG)
In this screen, the Navigation screen is displayed.
However, since hmi status of Phone call is FULL, the Navigation app moves the hmi status to LIMITED or BACKGROUND.
Thus, we cannot operate even though the navigation screen is displayed.
This proposal is to change the audible status to NOT_Audible in this case.

2021-08-06 16:08 UTC, jacobkeeler commented
@Akihiro-Miyazaki 

Alright I can see how this could be a useful case to cover for NAVIGATION app cases. I still don't agree that this would be good behavior for a MEDIA app, since the app would need to pause its audio during the event, it would definitely be better to switch to the phone call screen in that case.

That said, after testing this behavior out manually, it's very odd if the HMI doesn't switch to the phone call screen as of now, as there is no indication that the phone call officially started. If we want to make it so the HMI does not switch screens in some cases, then we would likely need to include a popup to indicate that the phone call was started, as is done in the example screenshots you provided.

Personally, with this consideration I believe that it would probably be better just to keep the current behavior (automatically switch to phone call screen regardless of app type) and just close this PR, as the addition of a phone call notification popup would probably be more work than it's worth in this case.

2021-08-17 08:30 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you for your comment and sorry for late response.
We think that the sdl system which uses the incoming call popup has a popup of phone call(talking?).
Also, we assume the sdl system has the both notification of incoming call and phone call(talking).
Is it correct?
If our recognition is wrong, we will close this PR according to your suggestion.
Because we think the screen transition is out of this proposal.

Just in case, does the close PR mean to close only this PR of sdl_hmi?
Could you please let us know if it has no problem to not close the PRs of sdl_core and sdl_atf_test_scripts and sdl_hmi_integration_guidelines?
Thank you.

2021-08-17 15:23 UTC, jacobkeeler commented
@Akihiro-Miyazaki The SDL HMI (I assume this is what you mean by "the sdl system"?) only uses a popup as a way to prompt the user to start the call and transition to the phone call screen. This popup does not persist after the phone call is started.
This HMI also does not have any support for incoming calls, any phone functionality is emulated for testing purposes.

As for the last question, we would only be closing this PR, all of the other ones (sdl_core, sdl_atf_test_scripts, etc.) would remain open because they are still necessary for the proposal (and they are also already approved, so they would likely be merged shortly after).

If this answers your questions and you don't have any more issues with keeping the current behavior, I can close this PR.

2021-08-18 06:22 UTC, Akihiro-Miyazaki commented
@jacobkeeler -san,
Thank you so much for your reply.
We understood.
Also, you have completed to answer all our question.
Therefore, we agree to close this PR.
Thank you for your cooperation.

2021-08-18 21:21 UTC, closed without merging