SDL 0192 Button Subscription response from HMI
smartdevicelink/sdl_hmi pull request #580
Opened 2021-07-20 13:28 UTC by ValeriiMalkov

Implements [#0192](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0192-button_subscription_response_from_hmi.md)

This PR is **ready** for review.

### Testing Plan
Manual testing

### Summary
Implemenation of Button Subscription response from HMI

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-07-23 12:41 UTC, ashwink11 commented
@jordynmackool this PR is ready for review and is approved by Ford.

2021-07-26 21:40 UTC, jacobkeeler requested changes

2021-07-26 21:40 UTC, jacobkeeler commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        vrAddComandSelect: Em.Select.extend({
```suggestion
        vrAddCommandSelect: Em.Select.extend({
```

2021-07-26 21:40 UTC, jacobkeeler commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        uiAddComandSelect: Em.Select.extend({
```suggestion
        uiAddCommandSelect: Em.Select.extend({
```

2021-07-26 21:40 UTC, jacobkeeler commented on css/settings.css
> +    ;
```suggestion
    left: 10px;
```

2021-07-26 21:40 UTC, jacobkeeler commented on ffw/RPCHelper.js
> +      if(resultCodeAsString === DO_NOT_RESPOND_RES_CODE) throw new Error(DO_NOT_RESPOND_RES_CODE);
I'd prefer if we just returned `'DO_NOT_RESPOND'` here, as is done for the other RPCs, rather than throwing an error.

2021-07-26 21:40 UTC, jacobkeeler commented on ffw/ButtonsRPC.js
> +            const resultCode = SDL.SDLModel.data.resultCode.SUCCESS;
Any reason that you can't set a custom result code for these?

2021-07-26 21:40 UTC, jacobkeeler commented on index.html
> +<script type="text/javascript" src="app/SDLApp.js"></script>
Any reason for rearranging this?

2021-07-26 21:40 UTC, jacobkeeler commented on ffw/RPCHelper.js
> +      }
```suggestion
       for(key in this.SubscribeButton){
         this.set(`SubscribeButton.${key}`, this.defaultSubscribeButton[key]);
       };
       for(key in this.UnsubscribeButton) {
         this.set(`UnsubscribeButton.${key}`,this.defaultUnsubscribeButton[key]);
       }
```

2021-07-28 12:32 UTC, LitvinenkoIra commented on app/controller/SettingsController.js
> +        SDL.RPCControlConfigView.UnSubscribeButton.initUnSubscribeButtonView();
Done 52fe15f0360c77df0bde13cd1d5cd3e69afe4d03

2021-07-28 12:32 UTC, LitvinenkoIra commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        vrAddComandSelect: Em.Select.extend({
Done 52fe15f0360c77df0bde13cd1d5cd3e69afe4d03

2021-07-28 12:32 UTC, LitvinenkoIra commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        uiAddComandSelect: Em.Select.extend({
Done 52fe15f0360c77df0bde13cd1d5cd3e69afe4d03

2021-07-28 12:32 UTC, LitvinenkoIra commented on css/settings.css
> +    ;
Done 52fe15f0360c77df0bde13cd1d5cd3e69afe4d03

2021-07-28 12:33 UTC, LitvinenkoIra commented on ffw/RPCHelper.js
> +      }
Done 52fe15f0360c77df0bde13cd1d5cd3e69afe4d03

2021-07-28 15:16 UTC, jacobkeeler requested changes

2021-07-28 20:37 UTC, jacobkeeler commented on capabilities/button_capabilities.js
> +]
```suggestion
]

```
nitpick

2021-08-04 18:07 UTC, theresalech commented
@ValeriiMalkov just checking in to make sure you've received Jacob's review. Please let us know if you have any questions or concerns with addressing his feedback. If you could also provide us with an anticipated date for when this PR will be ready for Livio's re-review, we'd appreciate it! Thank you!

2021-08-05 09:03 UTC, ValeriiMalkov commented on index.html
> +<script type="text/javascript" src="app/SDLApp.js"></script>
@jacobkeeler The `SDL` object is initialized in the` SDLApp.js` file. It is then used in `capabilities/*` files and in the `RPCHelper.js` file in the init method. It's kind of like a list of initializers. This is why the `SDLApp` needs to be initialized first.
The `features / *` files have been rearranged for the same reason, because `SDL.ButtonCapability` is called in the` init` method of the `RPCHelper.js` file below.

2021-08-05 09:20 UTC, ValeriiMalkov commented on ffw/ButtonsRPC.js
> +            const resultCode = SDL.SDLModel.data.resultCode.SUCCESS;
@jacobkeeler Custom result code not implemented for `NAVIGATION` buttons.

2021-08-05 10:19 UTC, ValeriiMalkov commented on ffw/RPCHelper.js
> +      if(resultCodeAsString === DO_NOT_RESPOND_RES_CODE) throw new Error(DO_NOT_RESPOND_RES_CODE);
@jacobkeeler Replaced in commit 03362eadc7fdfa7522f458088915bf527aa93266

2021-08-05 10:22 UTC, ValeriiMalkov commented on ffw/ButtonsRPC.js
> +              'capabilities': [...SDL.ButtonCapability, ...SDL.NAVButtonCapability],
@jacobkeeler Added to `display_capabilities.js`  in commit 7174dcbdc6105f5690196d862574baaef63fa619

2021-08-05 10:22 UTC, ValeriiMalkov commented on ffw/ButtonsRPC.js
> +                  SDL.SDLModel.data.resultCode.REJECTED,
@jacobkeeler Replaced 20e8abe2333eb7d89de7c97c85840b4b6c72e775

2021-08-05 10:23 UTC, ValeriiMalkov commented on ffw/ButtonsRPC.js
> +    subscribedButtons: {},
@jacobkeeler Tracking removed c99faa235d78904c3a07218cf94c0f49aee03ed1

2021-08-05 10:23 UTC, ValeriiMalkov commented on capabilities/button_capabilities.js
> +]
@jacobkeeler Fixed c99faa235d78904c3a07218cf94c0f49aee03ed1

2021-08-05 10:24 UTC, ValeriiMalkov commented
> @ValeriiMalkov just checking in to make sure you've received Jacob's review. Please let us know if you have any questions or concerns with addressing his feedback. If you could also provide us with an anticipated date for when this PR will be ready for Livio's re-review, we'd appreciate it! Thank you!

@theresalech  Thanks for the reminder. Comments done and ready for review.

2021-08-05 19:42 UTC, jacobkeeler requested changes

2021-08-05 19:42 UTC, jacobkeeler commented on ffw/ButtonsRPC.js
> +      }
Seems odd that this logic is in the function for `subscribeButton`, but it's outside of the function for `unsubscribeButton`. I think the `unsubscribeButton` approach would be more appropriate here, where the custom result code checking is done before calling this function

2021-08-05 19:42 UTC, jacobkeeler commented on ffw/ButtonsRPC.js
> +    navButtonSubscriptionToggle(appID, buttonName, subscribe) {
```suggestion
    setNavButtonSubscription(appID, buttonName, subscribe) {
```
This isn't really a toggle, since you pass the subscription flag in directly

2021-08-05 19:42 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
```suggestion
        "buttonCapabilities": SDL.ButtonCapability,
```
Seems to me there is no need to omit this value, since it is supported in this template

2021-08-05 19:42 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
```suggestion
        "buttonCapabilities": SDL.ButtonCapability,
```
No need to omit `CUSTOM_BUTTON`

2021-08-05 19:42 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name === 'CUSTOM_BUTTON'),
```suggestion
        "buttonCapabilities": [...SDL.NAVButtonCapability, ...SDL.ButtonCapability.filter(button => button.name === 'CUSTOM_BUTTON')],
```
Seems that the NAV button capabilities should be included here. Otherwise where are they supported?

2021-08-05 19:42 UTC, jacobkeeler commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        uiAddComandSelect: Em.Select.extend({
Still not fixed here, looks like the `ui` versions of this typo are still present

2021-08-05 19:42 UTC, jacobkeeler commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        vrAddComandlabel: SDL.Label.extend({
```suggestion
        vrAddCommandLabel: SDL.Label.extend({
```

2021-08-05 19:42 UTC, jacobkeeler commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        uiAddComandlabel: SDL.Label.extend({
```suggestion
        uiAddCommandLabel: SDL.Label.extend({
```

2021-08-06 09:34 UTC, ValeriiMalkov commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        uiAddComandlabel: SDL.Label.extend({
@jacobkeeler Fixed typo e19da15

2021-08-06 09:35 UTC, ValeriiMalkov commented on app/view/settings/RPCControls/RPCControlConfigView.js
> +        vrAddComandlabel: SDL.Label.extend({
@jacobkeeler Fixed typo e19da15

2021-08-06 09:36 UTC, ValeriiMalkov commented on ffw/ButtonsRPC.js
> +    navButtonSubscriptionToggle(appID, buttonName, subscribe) {
@jacobkeeler Renamed 54b806b8f86d11fff6043150b3826d7217489ce3

2021-08-06 09:37 UTC, ValeriiMalkov commented on ffw/ButtonsRPC.js
> +      }
@jacobkeeler Changed f62e0a41a506bdf0b404a44f6288421f632862d8

2021-08-06 10:46 UTC, ValeriiMalkov commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
@jacobkeeler As you can see, `CUSTOM_BUTTON` is ommited [in develop branch](https://github.com/smartdevicelink/sdl_hmi/blob/d58988ec3e1d00f619bcb88d68f5e3aff2fec312/capabilities/display_capabilities.js#L391)
Are you sure that is should be ommited?

2021-08-06 10:49 UTC, ValeriiMalkov commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
@jacobkeeler Ommited on [develop branch](https://github.com/smartdevicelink/sdl_hmi/blob/d58988ec3e1d00f619bcb88d68f5e3aff2fec312/capabilities/display_capabilities.js#L850)
I tried to leave it as a development branch.
Are you sure that is shouldn't be ommited?

2021-08-06 10:51 UTC, ValeriiMalkov commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name === 'CUSTOM_BUTTON'),
@jacobkeeler And [here on the develop branch](https://github.com/smartdevicelink/sdl_hmi/blob/d58988ec3e1d00f619bcb88d68f5e3aff2fec312/capabilities/display_capabilities.js#L1267) is only `CUSTOM_BUTTON`.
Are you sure it should be extended?

2021-08-06 13:43 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
I believe it should be included, yes. Regardless, this should be made consistent between templates. Currently only the `NAV_FULLSCREEN_MAP` includes this button, but it's supported by all templates.

2021-08-06 13:43 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
see this comment: https://github.com/smartdevicelink/sdl_hmi/pull/580#discussion_r684246053

2021-08-06 13:50 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name === 'CUSTOM_BUTTON'),
The capabilities on the develop branch definitely seem to be incorrect in this case. All of the NAV buttons are included in the main button capabilities, but aren't included in any individual template's capabilities. This template allows an app to subscribe to these buttons, so they should be included in the capabilities.

2021-08-06 16:55 UTC, iCollin commented on ffw/ButtonsRPC.js
> +            if (!FFW.RPCHelper.isSuccessResultCode(code)) {
```suggestion
            if (!FFW.RPCHelper.isSuccessResultCode(resultCode)) {
```

2021-08-09 09:29 UTC, ValeriiMalkov commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
@jacobkeeler Implemented 5563ddf80f22964bb8696a1735d8f2604accec06

2021-08-09 09:29 UTC, ValeriiMalkov commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'CUSTOM_BUTTON'),
@jacobkeeler Implemented 5563ddf80f22964bb8696a1735d8f2604accec06

2021-08-09 09:29 UTC, ValeriiMalkov commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name === 'CUSTOM_BUTTON'),
@jacobkeeler Implemented 5563ddf80f22964bb8696a1735d8f2604accec06

2021-08-09 09:29 UTC, ValeriiMalkov commented on ffw/ButtonsRPC.js
> +            if (!FFW.RPCHelper.isSuccessResultCode(code)) {
@iCollin Fixed 7dc86b82062c2a87d2f78513784685bda305d0ff

2021-08-10 20:29 UTC, jacobkeeler approved these changes
This PR looks good, although it looks like there is an issue where the capabilities do not update when switching templates. That is out of the scope of this feature though, so that can be fixed separately

2021-08-10 20:36 UTC, jacobkeeler requested changes

2021-08-10 20:36 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability,
```suggestion
        "buttonCapabilities": SDL.ButtonCapability.filter(button => button.name !== 'PLAY_PAUSE'),
```
Ah, looks like `PLAY_PAUSE` was not present in this template's capabilities originally

2021-08-10 20:37 UTC, jacobkeeler commented
Apologies, one more minor suggestion

2021-08-11 08:02 UTC, ValeriiMalkov commented on capabilities/display_capabilities.js
> +        "buttonCapabilities": SDL.ButtonCapability,
Done bc91ea36735350b9397a2a6a8444e89b0bdc2a48

2021-08-11 08:02 UTC, ValeriiMalkov commented
> Apologies, one more minor suggestion

Done bc91ea36735350b9397a2a6a8444e89b0bdc2a48

2021-08-11 13:03 UTC, jacobkeeler approved these changes

2021-08-12 18:47 UTC, merged