Fixed HMI does not apply Display mode to the main screen image
smartdevicelink/sdl_hmi pull request #584
Opened 2021-07-23 13:54 UTC by Ypostolov

Fixes(515)

This PR is **ready** for review.

### Testing Plan
SDL and HMI are started;mobile app is registered and activated;
Mobile application send “Show”(activate: “Graphic”,"imageType" = "DYNAMIC", .png, activate: “isTemplate”= ON),
than display mode changed, observe HMI applies display mode to the main screen image.

### Summary
Fixed HMI does not apply Display mode to the main screen image.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-08-05 20:43 UTC, ShobhitAd requested changes

2021-08-05 20:43 UTC, ShobhitAd commented on app/view/media/sdl/controllsView.js
> +            '<img {{bindAttr class="SDL.SDLController.model.isTemplate:ico-overlay"}} {{bindAttr class="SDL.SDLController.model.mediaPreset:cd_logoV2"}} {{bindAttr class="SDL.SDLController.model.mode
The ico overlay doesn't appear at the moment since it's missing the display mode class - `day-mode`, `night-mode` or `high-lighted-mode`
![templatedGraphicShow](https://user-images.githubusercontent.com/10703941/128418000-3e6efa90-ef7c-443d-b99f-8a8bb9a617d6.png)

2021-08-05 20:43 UTC, ShobhitAd commented on app/model/sdl/MediaModel.js
> +  imageModeChanged: function() {
Where is this callback triggered? I wasn't able to find a function call for this function in the sdl_hmi code

2021-08-05 20:43 UTC, ShobhitAd commented on app/model/sdl/MediaModel.js
>          default:this.set('mode','');
I think the imageMode should default to one of the modes instead of being empty (similar to how its handled in https://github.com/smartdevicelink/sdl_hmi/blob/master/app/controlls/Button.js#L95)

2021-08-07 03:09 UTC, AKalinich-Luxoft commented on app/view/media/sdl/controllsView.js
> +            '<img {{bindAttr class="SDL.SDLController.model.isTemplate:ico-overlay"}} {{bindAttr class="SDL.SDLController.model.mediaPreset:cd_logoV2"}} {{bindAttr class="SDL.SDLController.model.mode
@ShobhitAd good point, looks like we should track not only image mode, but also switching of template image parameter set by UI.Show
Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/584/commits/35507733bfcdfe7360b9c25f4dcfbd6f19b64acb

2021-08-07 03:10 UTC, AKalinich-Luxoft commented on app/model/sdl/MediaModel.js
> +  imageModeChanged: function() {
@ShobhitAd this is an observer function. It gets called automatically by framework whenever value of observable variable is updated

2021-08-07 03:10 UTC, AKalinich-Luxoft commented on app/model/sdl/MediaModel.js
>          default:this.set('mode','');
@ShobhitAd agree. Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/584/commits/35507733bfcdfe7360b9c25f4dcfbd6f19b64acb

2021-08-07 03:11 UTC, AKalinich-Luxoft commented
> The template overlay should probably also be implemented for images in NonMedia Layout https://github.com/smartdevicelink/sdl_hmi/blob/master/app/view/info/nonMediaView.js#L98

@ShobhitAd overlay logic has also been implemented for non media model in https://github.com/smartdevicelink/sdl_hmi/pull/584/commits/35507733bfcdfe7360b9c25f4dcfbd6f19b64acb

2021-08-10 13:40 UTC, ShobhitAd approved these changes

2021-08-10 13:40 UTC, merged