Fix/hmi doesnt update timeout prompt
smartdevicelink/sdl_hmi pull request #606
Opened 2021-09-14 10:28 UTC by ValeriiMalkov

Fixes [#599](https://github.com/smartdevicelink/sdl_hmi/issues/599)

This PR is **ready]** for review.

### Testing Plan
Manual testing

### Summary
The problem was requesting UI.PI after resetting the timeout. The timeout request did not update the timer.
Added an additional variable to save the timeout for the timeout prompt and the ability to reset it

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-09-14 10:29 UTC, ValeriiMalkov commented
Hi @theresalech This is a regression issue (related to OnResetTimeout feature) and PR is ready for Livio team review

2021-09-14 15:27 UTC, iCollin requested changes

2021-09-14 15:27 UTC, iCollin commented on app/controller/sdl/Abstract/Controller.js
> +      SDL.SDLModel.set('timeoutPromprtCallback', undefined);
```suggestion
      SDL.SDLModel.set('timeoutPromptCallback', undefined);
```

Typo in variable name

2021-09-15 08:31 UTC, ValeriiMalkov commented on app/controller/sdl/Abstract/Controller.js
> +      SDL.SDLModel.set('timeoutPromprtCallback', undefined);
@iCollin Fixed in 9198805

2021-09-15 13:09 UTC, merged