EndTime is not displayed when SetMediaClock set (UpdateMode=COUNTDOWN) with valid startTime and EndTime
smartdevicelink/sdl_hmi pull request #653
Opened 2021-11-23 12:27 UTC by ValeriiMalkov

Implements/Fixes [#627](https://github.com/smartdevicelink/sdl_hmi/issues/627)

This PR is **ready** for review.

### Testing Plan
Manual testing

### Summary
Added countdown timer displaying

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-11-23 12:28 UTC, ValeriiMalkov commented
Hi @theresalech ! This PR is ready for Livio team review!

2021-12-21 17:35 UTC, jacobkeeler requested changes

2021-12-21 17:35 UTC, jacobkeeler commented on app/model/sdl/MediaModel.js
> +            sec < 10 ? '0' : '') + sec;
Probably worth creating a helper function for this at this point:
```
    function time2str(time) {
        var position, str = '', hrs = 0, min = 0, sec = 0;
        hrs = parseInt(time / 3600), // hours
          min = parseInt(time / 60) % 60, // minutes
          sec = position % 60; // seconds

        str += " / ";
        str += (
            hrs < 10 ? '0' : '') + hrs + ':';
        str += (
            min < 10 ? '0' : '') + min + ':';
        str += (
            sec < 10 ? '0' : '') + sec;
      }
```

2021-12-21 18:48 UTC, jacobkeeler commented on app/model/sdl/MediaModel.js
> +        str += " / (-";
```suggestion
        str += " (-";
```
I don't think the `/` makes much sense here

2022-01-04 13:29 UTC, ValeriiMalkov commented on app/model/sdl/MediaModel.js
> +            sec < 10 ? '0' : '') + sec;
@jacobkeeler Please take a look changes in commit 89fa2416fa8f97edba1ae4555e9fefa8407735a6

2022-01-04 13:30 UTC, ValeriiMalkov commented on app/model/sdl/MediaModel.js
> +        str += " / (-";
@jacobkeeler Please take a look changes in commit 89fa2416fa8f97edba1ae4555e9fefa8407735a6

2022-01-04 14:30 UTC, jacobkeeler requested changes

2022-01-05 08:42 UTC, ValeriiMalkov commented on app/model/sdl/MediaModel.js
>          sec < 10 ? '0' : '') + sec;
@jacobkeeler Done in commit 2495b8c2bc31b9b5f020f185d9498942ed48367a

2022-01-05 14:57 UTC, jacobkeeler approved these changes

2022-01-05 14:57 UTC, merged