Fix issue: HMI doesn't stop play audio when PHONE_CALL event happend
smartdevicelink/sdl_hmi pull request #655
Opened 2021-12-01 11:16 UTC by LiliiaShlikhtLuxoft

Fixes [#654](https://github.com/smartdevicelink/sdl_hmi/issues/654)

This PR is **ready** for review.

### Testing Plan
Manual testing

### Summary
Created new function toggleMute in SDL.StreamAudio and added to SDL.SettingsController for phoneCall action.

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-12-01 11:17 UTC, LiliiaShlikhtLuxoft commented
Hi @theresalech ! PR is ready for Livio review.

2022-01-12 22:29 UTC, jacobkeeler requested changes

2022-01-12 22:29 UTC, jacobkeeler commented on app/util/StreamAudio.js
> +    this.audio.muted = !this.audio.muted;
```suggestion
  setMuted: function(muted) {
    this.audio.muted = muted;
```

Probably better to explicitly set this value, just to avoid running into issues where the state gets out of phase

2022-01-13 16:53 UTC, jacobkeeler requested changes
Also these calls should be added to the PhoneController as well

```
  /**
   *  Dial call handeler
   */
  onEndCall: function() {

    SDL.SDLController.onEventChanged('phoneCall', false);
+   SDL.StreamAudio.setMuted(false);
    this.model.endCall();
  },

  /**
   * Dial call handeler
   */
  onDialCall: function() {

    SDL.SDLController.onEventChanged('phoneCall', true);
+   SDL.StreamAudio.setMuted(true);
    this.model.dialCall();
  },
```

2022-01-14 14:13 UTC, LiliiaShlikhtLuxoft commented on app/util/StreamAudio.js
> +    this.audio.muted = !this.audio.muted;
Hi @jacobkeeler! Thank you for you comment! Please look at changes I've added in [commit](https://github.com/smartdevicelink/sdl_hmi/pull/655/commits/94af0c8fb50dbb6be4195e064316af787f63a9d3)

2022-01-14 15:11 UTC, jacobkeeler commented on app/controller/SettingsController.js
> +            SDL.StreamAudio.setMuted(true);
```suggestion
            SDL.StreamAudio.setMuted(false);
```

2022-01-14 15:13 UTC, jacobkeeler commented on app/controller/SettingsController.js
> +            SDL.StreamAudio.setMuted(true);
```suggestion
            SDL.StreamAudio.setMuted(false);
            if(SDL.SDLController.model && SDL.SDLController.model.appID !== appID) {
              return;
            }
            SDL.SDLController.getApplicationModel(appID).turnOnSDL(appID);
```
Seems that you deleted this code when you merged in develop, also the `muted` value should be `false` here

2022-01-17 09:40 UTC, LiliiaShlikhtLuxoft commented on app/controller/SettingsController.js
> +            SDL.StreamAudio.setMuted(true);
Hi @jacobkeeler! Please look at changes I've added in [commit](https://github.com/smartdevicelink/sdl_hmi/pull/655/commits/5a781c3a3c126315e03a2dc715184d145e6ab991)

2022-01-17 09:40 UTC, LiliiaShlikhtLuxoft commented on app/controller/SettingsController.js
> +            SDL.StreamAudio.setMuted(true);
Hi @jacobkeeler! Please look at changes I've added in [commit](https://github.com/smartdevicelink/sdl_hmi/pull/655/commits/5a781c3a3c126315e03a2dc715184d145e6ab991)

2022-01-18 15:10 UTC, jacobkeeler approved these changes

2022-01-18 15:10 UTC, merged