Fix/hmi displays the value for tts+vr application language over the section name
smartdevicelink/sdl_hmi pull request #660
Opened 2021-12-03 13:10 UTC by ValeriiMalkov

Implements/Fixes [#PR-657](https://github.com/smartdevicelink/sdl_hmi/issues/657)

This PR is **ready** for review.

### Testing Plan
Manual testing

### Summary
Fixed style for appTTSVRLang label

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-12-03 13:11 UTC, ValeriiMalkov commented
Hi @theresalech ! This PR is ready for livio team review!

2022-01-12 16:25 UTC, jacobkeeler requested changes
Seems like it would be cleaner to just shorten the content of the label

```
  /*
   * Label with name of UILanguages select
   */
  appUILanguagesLabel: SDL.Label.extend({

    elementId: 'appUILanguagesLabel',

    classNames: 'appUILanguagesLabel',

-   content: 'application UI Languages'
+   content: 'App UI Languages'
  }
),

  /*
   * Label with name of TTSVRLanguages select
   */
  appTTSVRLanguagesLabel: SDL.Label.extend({

    elementId: 'appTTSVRLanguagesLabel',

    classNames: 'appTTSVRLanguagesLabel',

-   content: 'application (TTS + VR) Languages'
+   content: 'App (TTS + VR) Languages'
  }
),
```

2022-01-13 09:30 UTC, ValeriiMalkov commented
> Seems like it would be cleaner to just shorten the content of the label
> 
> ```
>   /*
>    * Label with name of UILanguages select
>    */
>   appUILanguagesLabel: SDL.Label.extend({
> 
>     elementId: 'appUILanguagesLabel',
> 
>     classNames: 'appUILanguagesLabel',
> 
> -   content: 'application UI Languages'
> +   content: 'App UI Languages'
>   }
> ),
> 
>   /*
>    * Label with name of TTSVRLanguages select
>    */
>   appTTSVRLanguagesLabel: SDL.Label.extend({
> 
>     elementId: 'appTTSVRLanguagesLabel',
> 
>     classNames: 'appTTSVRLanguagesLabel',
> 
> -   content: 'application (TTS + VR) Languages'
> +   content: 'App (TTS + VR) Languages'
>   }
> ),
> ```

@jacobkeeler Take a look changes in commit 44dc48e

2022-01-13 16:59 UTC, jacobkeeler approved these changes

2022-01-13 16:59 UTC, merged