Fix/Add Missing WEB_VIEW display capabilities
smartdevicelink/sdl_hmi pull request #688
Opened 2022-07-20 20:55 UTC by ShobhitAd

Implements/Fixes #686

This PR is **ready** for review.

### Testing Plan
1. Start policy server
2. Add the following entry in sdl_preloaded_pt.json

```json
            "45b2c12c-a289-4c08-b4e4-bee768bf0cf9": {
                "AppHMIType": [ "WEB_VIEW" ],
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": ["Base-4", "WidgetSupport"],
                "hybrid_app_preference": "CLOUD",
                "enabled": false,
                "transport_type ": "WS"
            },
```

3. Change the `appStoreUrl` in Flags.js to `http://localhost:3000/api/v1/applications/store`
4. Start core and HMI
5. In the HMI, enable the "Hello Webengine3" app in the app store and activate the app
6. In the WEB_VIEW change the display layout to NON-MEDIA
7. Click on Options -> Return to WEB_VIEW

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-07-21 20:41 UTC, crokita approved these changes

2022-07-25 13:54 UTC, jacobkeeler requested changes

2022-07-25 13:54 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +                  }
Missing `menuIcon`,  `vrHelpItem`, `turnIcon`, `showConstantTBTIcon`, and `showConstantTBTNextTurnIcon`

2022-07-26 18:44 UTC, ShobhitAd commented on capabilities/display_capabilities.js
> +                }
Ah I was trying to match the WEB_VIEW capabilities with those in the generic hmi but I guess it makes sense that the navigation related textfields are not added in the generic hmi. 

That said, `menuName` and `secondaryText` should also probably be added in the generic hmi WEB_VIEW capabilities

2022-07-26 18:49 UTC, ShobhitAd commented on capabilities/display_capabilities.js
> +                  }
I think the [webengine projection proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0273-webengine-projection-mode.md#1-template-web_view) mentions that `menuIcon` should not be a part of the WEB_VIEW capabilities

> 4. The WEB_VIEW template must not declare support in its WindowCapabilities for any `softButtonCapabilities`, the TextFields with name: `mainField1-4`, `mediaClock`, `mediaTrack`, nor the ImageFields with name: `softButtonImage`, `menuIcon`, `graphic`, or `secondaryGraphic`.

But I can add in the other capabilities you mentioned

2022-07-26 19:10 UTC, ShobhitAd commented on capabilities/display_capabilities.js
> +                  }
Added in https://github.com/smartdevicelink/sdl_hmi/pull/688/commits/782bc5ca4258a040f0025ee9656795e8ff4872f1

2022-07-26 19:11 UTC, ShobhitAd commented on capabilities/display_capabilities.js
> +                },
Added in https://github.com/smartdevicelink/sdl_hmi/pull/688/commits/d12e03a814b11eaef5287c0afe83868d704335ec

2022-07-26 21:03 UTC, jacobkeeler commented on capabilities/display_capabilities.js
> +                  }
Ah, based on this proposal, it looks like the web view is supposed to display the menu button itself, so in that case we should probably also remove `menuTitle`

2022-07-26 21:16 UTC, jacobkeeler approved these changes

2022-07-26 21:19 UTC, jacobkeeler commented
Approving, though I will note two unrelated issues I found during testing
1. It seems `ONSCREEN_PRESETS` is missing from the template list of several of the templates.
2. Using the flow you gave in the PR description, I get an error. If you try to switch to `NON-MEDIA` from `WEB_VIEW` and back, it seems several things go wrong with the HMI state at the moment.

2022-07-29 15:12 UTC, crokita approved these changes

2022-07-29 16:26 UTC, merged